### ISSUE TITLE
`scipy.optimize.shgo` fails on minimizing variance

### ISSUE THREAD

**Issue by TMueller83** [scipy/scipy#10429]
The `shgo` optimizer from `scipy.optimize v1.3.0` fails on the relatively simple task to minimize the variance `var(x)` of a vector `x = [x1,...,xN]` with `0 <= xi <= 1` under the constraint, that `x` has a given average value. This problem can actually be solved easily by the `minimize` routine using the `SLSQP` method, therefore it is surprising, that `shgo` fails.

### Reproducing code example:
```python
import numpy as np
from scipy.optimize import shgo

# Constraint
avg = 0.5  # Given average value of x
cons = {'type': 'eq', 'fun': lambda x: np.mean(x)-avg}

# Minimize the variance of x under the given constraint
res = shgo(lambda x: np.var(x), bounds=6*[(0, 1)], constraints=cons)
```
#### Result
```python
>>> res
     fun: 0.0
 message: 'Failed to find a feasible minimiser point. Lowest sampling point = 0.0'
    nfev: 65
     nit: 2
   nlfev: 0
   nlhev: 0
   nljev: 0
 success: False
       x: array([0., 0., 0., 0., 0., 0.])
```

### Changing the bounds slightly solves the problem
```python
# Minimize the variance of x under the given constraint
res = shgo(lambda x: np.var(x), bounds=6*[(-0.1, 1)], constraints=cons)
```

#### Result
```python
>>> res
     fun: 1.0271626370065258e-32
    funl: array([1.02716264e-32, 3.23257763e-24])
 message: 'Optimization terminated successfully.'
    nfev: 1880
     nit: 2
   nlfev: 1815
   nlhev: 0
   nljev: 103
 success: True
       x: array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
      xl: array([[0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
       [0.45, 0.45, 0.45, 0.45, 0.45, 0.45]])
```

### The `minimize` routine can solve this problem
```python
from scipy.optimize import minimize
from numpy.random import random

x0 = random(6)  # Random start vector
res = minimize(lambda x: np.var(x), x0, bounds=6*[(0, 1)], constraints=cons)
```

#### Result
```python
>>> res
     fun: 7.385570535401643e-21
     jac: array([2.08738743e-09, 2.11824900e-09, 2.07106870e-09, 2.06780002e-09,
       2.03144003e-09, 2.04168917e-09])
 message: 'Optimization terminated successfully.'
    nfev: 32
     nit: 4
    njev: 4
  status: 0
 success: True
       x: array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
```

### Scipy/Numpy/Python version information:
```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.0 1.15.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by Stefan-Endres** [comment]
Short, user end answers:
- 
- `shgo` unexpectedly fails due to an implementation detail in the default sampling step of the algorithm, this detail should be improved in future sampling step performance improvements.
- Either incorporating the constraint in the objective function or using a different sampling method should solve the problem, for example:

```python
import numpy as np
from scipy.optimize import shgo

N = 6

# Constraint parameter
avg = 0.5  # Given average value of x

# Minimize the variance of x
res = shgo(lambda x: np.var(np.append(x, N * avg - np.sum(x))), bounds=(N - 1)*[(0, 1)])

# Print outputs
print(res) 
print(f' Solution vector = { np.append(res.x, N * avg - np.sum(res.x)) }') 
```
output:
```python
>>> print(res) 
     fun: 0.0
    funl: array([0.])
 message: 'Optimization terminated successfully.'
    nfev: 40
     nit: 2
   nlfev: 7
   nlhev: 0
   nljev: 1
 success: True
       x: array([0.5, 0.5, 0.5, 0.5, 0.5])
      xl: array([[0.5, 0.5, 0.5, 0.5, 0.5]])
>>> print(f' Solution vector = { np.append(res.x, N * avg - np.sum(res.x)) }') 
 Solution vector = [0.5 0.5 0.5 0.5 0.5 0.5]

```

- I would highly recommend using a local solver with a random starting point anyway as the initialisation cost of a global solver alone is not worth it on this problem. In addition the trade off of finding an improved starting point is not worth the cost. For example using the point supplied from `shgo`, `SLSQP` used 7 function evaluations and 1 Jacobian compared to 32 function and 4 Jacobian evaluations using a random starting point. However, the `shgo` minimiser point came at a cost of 33 function evaluations in the global sampling step anyway, plus the increased initialisation time of the global solver object.

Detailed answers for development:
-
Visualising this problem in the lower dimension (`N = 2`) it appears that the algorithm fails due to the default sampling pattern, which is not expecting such structured problems. For example here we plot the simplicial complex approximation of the default sampling method on the objective function surface (here `f` is the objective function or variance and `x1` and `x2` are the variables or vector components):

![stck1](https://user-images.githubusercontent.com/8235072/60883536-bcc7c880-a24a-11e9-8e85-c344aed0ec32.png)

As the contour plot below shows there is no minimiser point on this surface since the objective function value is the same for all the points on the  `x2 = x1` line:

 ![stck2](https://user-images.githubusercontent.com/8235072/60883545-c05b4f80-a24a-11e9-8e3e-a993fee7b8e9.png)

Refining the sampling does not improve the situation because of the symmetry in the sampling pattern:

![stck3](https://user-images.githubusercontent.com/8235072/60884281-d702a600-a24c-11e9-8680-cce6927194c0.png)

![stck4](https://user-images.githubusercontent.com/8235072/60884295-dc5ff080-a24c-11e9-8b05-c000b7f804da.png)

This explains why changing the bounds slightly lets the algorithm find a minimiser that leads to a solution. 

After reformulating the problem by including the constraint in the objective function the algorithm easily finds a minimiser. This is due the reformulation providing a strictly convex surface.  The minimiser point is plotted here as a red dot on the surface (here we consider a 3-dimensional vector (`N = 3`), however, we have only 2 variables so can visualise it):

![stck5](https://user-images.githubusercontent.com/8235072/60884501-4d9fa380-a24d-11e9-8d58-d3bddc8ff690.png)

![stck6](https://user-images.githubusercontent.com/8235072/60884507-51cbc100-a24d-11e9-8d3a-99d7238924e2.png)

For the (`N = 2`) case the problem is a simple quadratic function:

![stck7](https://user-images.githubusercontent.com/8235072/60887661-2cdb4c00-a255-11e9-835a-2d445b8d34c4.png)


More quasi random sampling algorithms (including the available Sobol sampling generation method) should not run into issues like this. While a local solver is far more appropriate due to the simple convex structure of this problem, the default behaviour of `shgo` should be to round off the best current solution by passing it the local solver, rather than only returning the best sampling point. 

In the context of global optimisation the algorithm would try to increase the sampling points until a promising point is found (for example when the objective function is a table top with sparse values at lower objective values). However, an implementation of a global optimisation algorithm should be expected to easily converge on simpler problems so a round off should occur in case of other well structured, symmetric problems have this issue (since they may be black box with unknown, hidden structure). This is simple to implement by passing the lowest sampling point to a local solver every iteration regardless of whether a feasible minimiser is found in the sampling stage

This will be fixed in the upstream repository and bundled with a performance improvement PR to scipy.

**Comment by TMueller83** [comment]
Thank you very much @Stefan-Endres for your super detailed answer and explanations! The problem of minimizing the variance `var(x)` was of course just a little toy problem in order to get warm with the `shgo` method and to test its performance.

Your approach of incorporating the constraint directly into the objective function is a great idea! However, it is almost certain that in doing so the objective function will be called outside of its allowed domain `[0, 1]**N` (which is no problem for the simple objective function `var(x)`, but real-world functions could be ill-defined outside of their domain), such that reasonable continuations must be added to the objective function.

Using the `sobol` sampling algorithm as you suggested also works very well. Probably this is the way to go for me until improved sampling methods will be implemented in the future.

Until then, thank you very much again for making the effort of providing such a nice detailed answer with beautiful visualizations!

**Comment by mdhaber** [comment]
Sometimes optimization algorithms fail to solve problems, and `shgo` is correctly reporting the failure. This doesn't sound like a bug, so I've changed the label from "defect" to "enhancement" since the request is to improve the ability of `shgo` to solve this problem.

**Comment by mdhaber** [comment]
@Stefan-Endres You marked that gh-16313 would close this, but the original code still fails; the user must pass `n` explicitly (e.g. `n=99` to solve the problem. Is this problem pathological, or is it reasonable to keep this enhancement request (for `shgo` to solve the problem with default settings) open?

**Comment by Stefan-Endres** [comment]
Similar to https://github.com/scipy/scipy/issues/10538#issuecomment-1407454951, I will unmark in gh-16313 and open a separate PR at a later date.
