### ISSUE TITLE
scipy.test() failure in TestInterop.test_splrep_errors

### ISSUE THREAD

**Issue by mjswartz3141** [scipy/scipy#10704]
I am running scipy.test() with Python 3.6 and scipy 1.3.1. The failure report is below. Sorry for its length, just trying to be thorough. Let me know whatever other information is needed.

================================================================================================= FAILURES =================================================================================================

______________________________________________________________________________________ TestInterop.test_splrep_errors ______________________________________________________________________________________

self = <scipy.interpolate.tests.test_bsplines.TestInterop object at 0x7f12046f40b8>

    @pytest.mark.xfail(NumpyVersion(np.__version__) < '1.14.0',
                       reason='requires NumPy >= 1.14.0')
    def test_splrep_errors(self):
        # test that both "old" and "new" splrep raise for an n-D ``y`` array
        # with n > 1
        x, y = self.xx, self.yy
        y2 = np.c_[y, y]
        with assert_raises(ValueError):
>           splrep(x, y2)

self       = <scipy.interpolate.tests.test_bsplines.TestInterop object at 0x7f12046f40b8>
x          = array([ 0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
        1.57079633,  1.88495559,  2.19911486, ... 10.36725576, 10.68141502,
       10.99557429, 11.30973355, 11.62389282, 11.93805208, 12.25221135,
       12.56637061])
y          = array([ 1.00000000e+00,  9.51056516e-01,  8.09016994e-01,  5.87785252e-01,
        3.09016994e-01,  6.12323400e-17, -3...1, -4.28626380e-16,
        3.09016994e-01,  5.87785252e-01,  8.09016994e-01,  9.51056516e-01,
        1.00000000e+00])
y2         = array([[ 1.00000000e+00,  1.00000000e+00],
       [ 9.51056516e-01,  9.51056516e-01],
       [ 8.09016994e-01,  8.0901....09016994e-01,  8.09016994e-01],
       [ 9.51056516e-01,  9.51056516e-01],
       [ 1.00000000e+00,  1.00000000e+00]])

../../../../.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/interpolate/tests/test_bsplines.py:626: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/interpolate/fitpack.py:289: in splrep
    res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = array([ 0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
        1.57079633,  1.88495559,  2.19911486, ... 10.36725576, 10.68141502,
       10.99557429, 11.30973355, 11.62389282, 11.93805208, 12.25221135,
       12.56637061])
y = array([[ 1.00000000e+00,  1.00000000e+00],
       [ 9.51056516e-01,  9.51056516e-01],
       [ 8.09016994e-01,  8.0901....09016994e-01,  8.09016994e-01],
       [ 9.51056516e-01,  9.51056516e-01],
       [ 1.00000000e+00,  1.00000000e+00]])
w = array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.]), xb = 0.0
xe = 12.566370614359172, k = 3, task = 0, s = 0.0
t = array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.62831853,
        0.9424778 ,  1.25663706,  1.57079633, ...141502, 10.99557429, 11.30973355, 11.62389282,
       11.93805208, 12.56637061, 12.56637061, 12.56637061, 12.56637061])
full_output = 0, per = 0, quiet = 1

    def splrep(x, y, w=None, xb=None, xe=None, k=3, task=0, s=None, t=None,
               full_output=0, per=0, quiet=1):
        """
        Find the B-spline representation of 1-D curve.
    
        Given the set of data points ``(x[i], y[i])`` determine a smooth spline
        approximation of degree k on the interval ``xb <= x <= xe``.
    
        Parameters
        ----------
        x, y : array_like
            The data points defining a curve y = f(x).
        w : array_like, optional
            Strictly positive rank-1 array of weights the same length as x and y.
            The weights are used in computing the weighted least-squares spline
            fit. If the errors in the y values have standard-deviation given by the
            vector d, then w should be 1/d. Default is ones(len(x)).
        xb, xe : float, optional
            The interval to fit.  If None, these default to x[0] and x[-1]
            respectively.
        k : int, optional
            The order of the spline fit. It is recommended to use cubic splines.
            Even order splines should be avoided especially with small s values.
            1 <= k <= 5
        task : {1, 0, -1}, optional
            If task==0 find t and c for a given smoothing factor, s.
    
            If task==1 find t and c for another value of the smoothing factor, s.
            There must have been a previous call with task=0 or task=1 for the same
            set of data (t will be stored an used internally)
    
            If task=-1 find the weighted least square spline for a given set of
            knots, t. These should be interior knots as knots on the ends will be
            added automatically.
        s : float, optional
            A smoothing condition. The amount of smoothness is determined by
            satisfying the conditions: sum((w * (y - g))**2,axis=0) <= s where g(x)
            is the smoothed interpolation of (x,y). The user can use s to control
            the tradeoff between closeness and smoothness of fit. Larger s means
            more smoothing while smaller values of s indicate less smoothing.
            Recommended values of s depend on the weights, w. If the weights
            represent the inverse of the standard-deviation of y, then a good s
            value should be found in the range (m-sqrt(2*m),m+sqrt(2*m)) where m is
            the number of datapoints in x, y, and w. default : s=m-sqrt(2*m) if
            weights are supplied. s = 0.0 (interpolating) if no weights are
            supplied.
        t : array_like, optional
            The knots needed for task=-1. If given then task is automatically set
            to -1.
        full_output : bool, optional
            If non-zero, then return optional outputs.
        per : bool, optional
            If non-zero, data points are considered periodic with period x[m-1] -
            x[0] and a smooth periodic spline approximation is returned. Values of
            y[m-1] and w[m-1] are not used.
        quiet : bool, optional
            Non-zero to suppress messages.
            This parameter is deprecated; use standard Python warning filters
            instead.
    
        Returns
        -------
        tck : tuple
            (t,c,k) a tuple containing the vector of knots, the B-spline
            coefficients, and the degree of the spline.
        fp : array, optional
            The weighted sum of squared residuals of the spline approximation.
        ier : int, optional
            An integer flag about splrep success. Success is indicated if ier<=0.
            If ier in [1,2,3] an error occurred but was not raised. Otherwise an
            error is raised.
        msg : str, optional
            A message corresponding to the integer flag, ier.
    
        Notes
        -----
        See splev for evaluation of the spline and its derivatives.
    
        The user is responsible for assuring that the values of *x* are unique.
        Otherwise, *splrep* will not return sensible results.
    
        See Also
        --------
        UnivariateSpline, BivariateSpline
        splprep, splev, sproot, spalde, splint
        bisplrep, bisplev
    
        Notes
        -----
        See splev for evaluation of the spline and its derivatives. Uses the
        FORTRAN routine curfit from FITPACK.
    
        If provided, knots `t` must satisfy the Schoenberg-Whitney conditions,
        i.e., there must be a subset of data points ``x[j]`` such that
        ``t[j] < x[j] < t[j+k+1]``, for ``j=0, 1,...,n-k-2``.
    
        References
        ----------
        Based on algorithms described in [1]_, [2]_, [3]_, and [4]_:
    
        .. [1] P. Dierckx, "An algorithm for smoothing, differentiation and
           integration of experimental data using spline functions",
           J.Comp.Appl.Maths 1 (1975) 165-184.
        .. [2] P. Dierckx, "A fast algorithm for smoothing data on a rectangular
           grid while using spline functions", SIAM J.Numer.Anal. 19 (1982)
           1286-1304.
        .. [3] P. Dierckx, "An improved algorithm for curve fitting with spline
           functions", report tw54, Dept. Computer Science,K.U. Leuven, 1981.
        .. [4] P. Dierckx, "Curve and surface fitting with splines", Monographs on
           Numerical Analysis, Oxford University Press, 1993.
    
        Examples
        --------
    
        >>> import matplotlib.pyplot as plt
        >>> from scipy.interpolate import splev, splrep
        >>> x = np.linspace(0, 10, 10)
        >>> y = np.sin(x)
        >>> tck = splrep(x, y)
        >>> x2 = np.linspace(0, 10, 200)
        >>> y2 = splev(x2, tck)
        >>> plt.plot(x, y, 'o', x2, y2)
        >>> plt.show()
    
        """
        if task <= 0:
            _curfit_cache = {}
        x, y = map(atleast_1d, [x, y])
        m = len(x)
        if w is None:
            w = ones(m, float)
            if s is None:
                s = 0.0
        else:
            w = atleast_1d(w)
            if s is None:
                s = m - sqrt(2*m)
        if not len(w) == m:
            raise TypeError('len(w)=%d is not equal to m=%d' % (len(w), m))
        if (m != len(y)) or (m != len(w)):
            raise TypeError('Lengths of the first three arguments (x,y,w) must '
                            'be equal')
        if not (1 <= k <= 5):
            raise TypeError('Given degree of the spline (k=%d) is not supported. '
                            '(1<=k<=5)' % k)
        if m <= k:
            raise TypeError('m > k must hold')
        if xb is None:
            xb = x[0]
        if xe is None:
            xe = x[-1]
        if not (-1 <= task <= 1):
            raise TypeError('task must be -1, 0 or 1')
        if t is not None:
            task = -1
        if task == -1:
            if t is None:
                raise TypeError('Knots must be given for task=-1')
            numknots = len(t)
            _curfit_cache['t'] = empty((numknots + 2*k + 2,), float)
            _curfit_cache['t'][k+1:-k-1] = t
            nest = len(_curfit_cache['t'])
        elif task == 0:
            if per:
                nest = max(m + 2*k, 2*k + 3)
            else:
                nest = max(m + k + 1, 2*k + 3)
            t = empty((nest,), float)
            _curfit_cache['t'] = t
        if task <= 0:
            if per:
                _curfit_cache['wrk'] = empty((m*(k + 1) + nest*(8 + 5*k),), float)
            else:
                _curfit_cache['wrk'] = empty((m*(k + 1) + nest*(7 + 3*k),), float)
            _curfit_cache['iwrk'] = empty((nest,), intc)
        try:
            t = _curfit_cache['t']
            wrk = _curfit_cache['wrk']
            iwrk = _curfit_cache['iwrk']
        except KeyError:
            raise TypeError("must call with task=1 only after"
                            " call with task=0,-1")
        if not per:
            n, c, fp, ier = dfitpack.curfit(task, x, y, w, t, wrk, iwrk,
>                                           xb, xe, k, s)
E           dfitpack.error: failed in converting 3rd argument `y' of dfitpack.curfit to C/Fortran array

_curfit_cache = {'iwrk': array([   55032256,           0,  -547680393,  1070926854,  -812561380,
        1070907834,  1201389454,  107...00e+000, 4.03087768e-098, 1.00000000e+000,
       2.97773432e-100, 1.00000000e+000, 1.97930035e-102, 1.00000000e+000])}
full_output = 0
iwrk       = array([   55032256,           0,  -547680393,  1070926854,  -812561380,
        1070907834,  1201389454,  1070808744, ...,   762507841,  1069583366,
       -1122429777,  1069158440,  -958381132,  1068836914,           0],
      dtype=int32)
k          = 3
m          = 41
nest       = 45
per        = 0
quiet      = 1
s          = 0.0
t          = array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.62831853,
        0.9424778 ,  1.25663706,  1.57079633, ...141502, 10.99557429, 11.30973355, 11.62389282,
       11.93805208, 12.56637061, 12.56637061, 12.56637061, 12.56637061])
task       = 0
w          = array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])
wrk        = array([6.90297340e-310, 6.90297340e-310, 2.98387192e-316, 2.98387192e-316,
       0.00000000e+000, 1.66666667e-001, 6....000e+000, 4.03087768e-098, 1.00000000e+000,
       2.97773432e-100, 1.00000000e+000, 1.97930035e-102, 1.00000000e+000])
x          = array([ 0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
        1.57079633,  1.88495559,  2.19911486, ... 10.36725576, 10.68141502,
       10.99557429, 11.30973355, 11.62389282, 11.93805208, 12.25221135,
       12.56637061])
xb         = 0.0
xe         = 12.566370614359172
y          = array([[ 1.00000000e+00,  1.00000000e+00],
       [ 9.51056516e-01,  9.51056516e-01],
       [ 8.09016994e-01,  8.0901....09016994e-01,  8.09016994e-01],
       [ 9.51056516e-01,  9.51056516e-01],
       [ 1.00000000e+00,  1.00000000e+00]])

../../../../.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/interpolate/_fitpack_impl.py:502: error
------------------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------------------
too many axes: 2 (effrank=2), expected rank=1
============================================================================================= warnings summary =============================================================================================
/home/swartz/.virtualenvs/dl4cv/lib/python3.6/distutils/__init__.py:4
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
/home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/_pytest/mark/structures.py:324: PytestUnknownMarkWarning: Unknown pytest.mark.xslow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

ndimage/tests/test_ndimage.py::TestNdimage::test_geometric_transform_endianness_with_output_parameter
ndimage/tests/test_ndimage.py::TestNdimage::test_geometric_transform_endianness_with_output_parameter
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:262: DeprecationWarning: NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INOUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.
    extra_keywords)

ndimage/tests/test_ndimage.py::TestNdimage::test_geometric_transform_endianness_with_output_parameter
ndimage/tests/test_ndimage.py::TestNdimage::test_geometric_transform_endianness_with_output_parameter
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:262: DeprecationWarning: UPDATEIFCOPY detected in array_dealloc.  Required call to PyArray_ResolveWritebackIfCopy or PyArray_DiscardWritebackIfCopy is missing
    extra_keywords)

ndimage/tests/test_ndimage.py::TestNdimage::test_map_coordinates_endianness_with_output_parameter
ndimage/tests/test_ndimage.py::TestNdimage::test_map_coordinates_endianness_with_output_parameter
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:350: DeprecationWarning: NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INOUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.
    output, order, mode, cval, None, None)

ndimage/tests/test_ndimage.py::TestNdimage::test_map_coordinates_endianness_with_output_parameter
ndimage/tests/test_ndimage.py::TestNdimage::test_map_coordinates_endianness_with_output_parameter
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:350: DeprecationWarning: UPDATEIFCOPY detected in array_dealloc.  Required call to PyArray_ResolveWritebackIfCopy or PyArray_DiscardWritebackIfCopy is missing
    output, order, mode, cval, None, None)

ndimage/tests/test_ndimage.py::TestNdimage::test_affine_transform_1d_endianness_with_output_parameter
ndimage/tests/test_ndimage.py::TestNdimage::test_affine_transform_1d_endianness_with_output_parameter
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:483: DeprecationWarning: NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INOUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.
    mode, cval)

ndimage/tests/test_ndimage.py::TestNdimage::test_affine_transform_1d_endianness_with_output_parameter
ndimage/tests/test_ndimage.py::TestNdimage::test_affine_transform_1d_endianness_with_output_parameter
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:483: DeprecationWarning: UPDATEIFCOPY detected in array_dealloc.  Required call to PyArray_ResolveWritebackIfCopy or PyArray_DiscardWritebackIfCopy is missing
    mode, cval)

ndimage/tests/test_ndimage.py::TestNdimage::test_affine_transform_multi_d_endianness_with_output_parameter
ndimage/tests/test_ndimage.py::TestNdimage::test_affine_transform_multi_d_endianness_with_output_parameter
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:486: DeprecationWarning: NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INOUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.
    output, order, mode, cval, None, None)

ndimage/tests/test_ndimage.py::TestNdimage::test_affine_transform_multi_d_endianness_with_output_parameter
ndimage/tests/test_ndimage.py::TestNdimage::test_affine_transform_multi_d_endianness_with_output_parameter
  /home/swartz/.virtualenvs/dl4cv/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:486: DeprecationWarning: UPDATEIFCOPY detected in array_dealloc.  Required call to PyArray_ResolveWritebackIfCopy or PyArray_DiscardWritebackIfCopy is missing
    output, order, mode, cval, None, None)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================== 1 failed, 14525 passed, 1274 skipped, 1225 deselected, 77 xfailed, 8 xpassed, 26 warnings in 234.09s (0:03:54) ==============================================`

**Comment by tylerjereddy** [comment]
This looks very similar to https://github.com/scipy/scipy/issues/9777, and I think the conditional `xfail` was supposed to handle the matter...

**Comment by mjswartz3141** [comment]
Would this be solved by having specific versions of scipy and numpy as in the 9777 post?

**Comment by melissawm** [comment]
Hi, not sure if this is related, but I'm also getting a similar failure of scipy.test() with SciPy 1.4.0.dev0+a6bd045, numpy 1.17.2. Here's the final output:

```
scipy/scipy/interpolate/_fitpack_impl.py:502: error
-------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
too many axes: 2 (effrank=2), expected rank=1
=============================== 1 failed, 17931 passed, 1289 skipped, 1079 deselected, 76 xfailed, 8 xpassed in 411.44 seconds
```

Let me know if this is not the right place or if I can help with more info.

**Comment by bremoore** [comment]
Has there been any resolution for this? I'm getting very similar results from scipy.test() as op. I was trying to do cross validation in a jupyter notebook with n_jobs = -1. If I run without n_jobs set, it runs slowly, but it works.
```bash
PytestUnknownMarkWarning: Unknown pytest.mark.xslow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
= 14529 passed, 1272 skipped, 1225 deselected, 77 xfailed, 7 xpassed, 9 warnings in 255.03s (0:04:15) =
True
```

<img width="1041" alt="Screen Shot 2019-10-22 at 4 26 16 PM" src="https://user-images.githubusercontent.com/23564937/67343044-e13d6d00-f4e8-11e9-8795-adc407745719.png">

**Comment by tylerjereddy** [comment]
This problem is still real in latest master branch & is causing 3 failures in our wheel build repo master branch. Here's a sample log: https://api.travis-ci.org/v3/job/642208588/log.txt

The failure is only observed on Python 3.6 in wheels repo: either 32- or 64-bit Linux & MacOS

Here's the traceback:

```
________________________ TestInterop.test_splrep_errors ________________________
[gw0] linux -- Python 3.6.8 /venv/bin/python
/venv/lib/python3.6/site-packages/scipy/interpolate/tests/test_bsplines.py:626: in test_splrep_errors
    splrep(x, y2)
/venv/lib/python3.6/site-packages/scipy/interpolate/fitpack.py:289: in splrep
    res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
/venv/lib/python3.6/site-packages/scipy/interpolate/_fitpack_impl.py:502: in splrep
    xb, xe, k, s)
E   dfitpack.error: failed in converting 3rd argument `y' of dfitpack.curfit to C/Fortran array
----------------------------- Captured stderr call 
```

**Comment by ev-br** [comment]
This test can be just skipped for older numpy.
Or removed altogether, really.

**Comment by ev-br** [comment]
@tylerjereddy so this is no longer seen, correct? IIUC it's something related to numpy/f2py and the underlying problem has been fixed in the lowest supported NumPy version.

**Comment by tylerjereddy** [comment]
Sounds right, plus 3.6 is not relevant for the wheels repo `master` branch anymore of course. So, I'll close.
