### ISSUE TITLE
Add note in documentation

### ISSUE THREAD

**Issue by santinoacco** [scipy/scipy#12073]
https://github.com/scipy/scipy/blob/adc4f4f7bab120ccfab9383aba272954a0a12fb0/scipy/stats/stats.py#L4999

So in computing this test you are implicitly assuming that the null hipothesis of the test is build like:
```tex
 <mean1> - <mean2> = 0.
```
But one could build it the other way:
```tex
<mean2> - <mean1> = 0.
```

Now this supposes no issue if we are only interested on the two-sided test. However since it is possible to derive the result of a one-side test from the two-sided test result, it is important to know which of the assumptions you are making in order to avoid miss interpretations of the results.

So it is okay if you make the hipothesis like this
 ```tex
d = <mean1> - <mean2> = 0.
```
but that information should be available and clear in the documentation.
Thanks in advance

**Comment by mdhaber** [comment]
Seems like a good first issue: add the definition of the t-statistic to the notes of the `ttest_` functions in `scipy.stats` and `scipy.stats.mstats`.

**Comment by jacoblapenna** [comment]
I'll see if I can fix this as a first issue/contribution.

**Comment by jacoblapenna** [comment]
@mdhaber looking deeper into this issue, this was already addressed in November, 2020 (~6 months after this issue was opened) via [issue #12597](https://github.com/scipy/scipy/pull/12597) with the details of the commit [here](https://github.com/scipy/scipy/commit/97c42a65b4233ad51e4d88156fda9ac169c0f284). Specifically, the `alternative` argument and functionality was implemented, and now one-sided or two-sided t-tests can be performed explicitly. @santinoacco your issue is referencing old source, instead of calculating one-sided t-tests from two-sided results, you can now explicitly call a one-sided test. @mdhaber I think this issue can be closed without a PR.

**Comment by mdhaber** [comment]
Hi @jacoblapenna, thanks for participating in the sprint today! I've actually been organizing the addition of the `alternative` argument to our statistical tests (e.g. gh-12506), so I know `alternative` was added, but the [current documentation ](
https://31061-1460385-gh.circle-artifacts.com/0/html-scipyorg/reference/generated/scipy.stats.ttest_ind.html#scipy.stats.ttest_ind) still doesn't explicitly define 

1) the direction in which the statistic is calculated or 
2) the meaning of the alternatives (e.g. what does `less` mean?). 

gh-13958 will address part 2 of that, but even there it is still not 100% explicit the direction in which the statistic itself is calculated. 

It can easily be inferred, e.g.:
```python3
import numpy as np
from scipy import stats
x = stats.norm.rvs(size=20, loc=0)
y = stats.norm.rvs(size=20, loc=-1)
stats.ttest_ind(x, y, alternative='greater')  # Ttest_indResult(statistic=3.4199113882148624, pvalue=0.0007549805130888606)
```

1) Because `statistic` is positive, the statistic must be calculated using `x.mean() - y.mean()` rather than the other way around.
2) Because the p-value is small, "greater" must refer to the mean of `x` being _greater_ than the mean of `y`.

But it is not currently explicit in the documentation, so I still think that giving the definition of the t-statistic would be an improvement.
