### ISSUE TITLE
shgo is not correctly passing jac to minimizer

### ISSUE THREAD

**Issue by lola-anderson** [scipy/scipy#12963]
I am getting  the "_minimize_slsqp() got multiple values for argument 'jac' " error for my toy example below. Is this a bug in shgo or am I doing something wrong? Please advise if there is a workaround.

```
from scipy.optimize import shgo

def objective(x):
    return 3*x[0]*x[0] + 2*x[0] + 5

def objective_jac(x):
    return 6*x[0] + 2

if __name__ == "__main__":

    bounds = [(-100, 100)]

    result = shgo(objective, bounds, options={'jac':objective_jac})
    print(result)
```

**Comment by pmla** [comment]
This appears to be a mistake in the documentation. The `jac` parameter should be passed in the `minimizer_kwargs` dictionary rather than int `options`.

@Stefan-Endres would you like to make a fix? I think the `hess` parameter is also in the wrong place.

**Comment by Stefan-Endres** [comment]
Thank you for tagging me @pmla.

You are right that passing to `minimizer_kwargs` works and the documentation is wrong. I will make a quick fix to update the `minimizer_kwargs` with `jac` and `hess` after it has been constructed in the `__init__` function this should solve the problem.


The original intention with passing it to the `options` was to allow both global and local use of the Jacobian (for example global use is when computing Lipschitz constants in the global sampling step to stop sampling well explored areas) without the need to define it twice. So this is a bug rather than a mistake in the documentation as it should only be needed for the user to define it once in a dictionary (defined in the `options` dict and then passed to `minimizer_kwargs` if and only if the local solver supports it).

**Comment by mdhaber** [comment]
@Stefan-Endres why did we just go through the trouble of gh-17140 rather than just adjusting the documentation? 

Even after gh-16313 merges, SHGO still doesn't use `jac`, `hess`, or `hessp`. It would have been a whole lot simpler to just remove them from the list of SHGO options, right?

**Comment by Stefan-Endres** [comment]
@mdhaber yes you are right. The original reason for it being there was to compute local Lipschitz constants to improve the global sampling quality which greatly improves the performance on a large class of optimisation problems (and the flexibility would be that local solvers that don't use the gradient can be still chosen when needed), but this feature was not stable and is not currently included. For now it is just ease for the user to specify only in one of the dictionaries. 

I therefore think it is worth keeping it as it currently is, but I would also be happy to revert the changes and change the documentation.
