### ISSUE TITLE
missing python 3.8 manylinux wheels on scipy-wheels-nightly

### ISSUE THREAD

**Issue by keewis** [scipy/scipy#13540]
I'm opening this issue here for increased visibility: it seems the wheel repository is consistently [failing](https://dev.azure.com/numpy/numpy/_build/results?buildId=15359&view=results) because of a single test failure on linux with python 3.8 since Jan 10, resulting in missing python 3.8 manylinux wheels on `scipy-wheels-nightly`.

<details><summary>error message</summary>

linux amd64-linux-py38:
```
[gw0] linux -- Python 3.8.1 /venv/bin/python
worker 'gw0' crashed while running 'stats/tests/test_stats.py::Test_ttest_ind_permutations::test_ttest_ind_randperm_alternative2'
```

linux 32bit-amd64-linux-py38:
```
_______ Test_ttest_ind_permutations.test_ttest_ind_randperm_alternative2 _______
[gw0] linux -- Python 3.8.1 /venv/bin/python
/venv/lib/python3.8/site-packages/scipy/stats/tests/test_stats.py:4003: in test_ttest_ind_randperm_alternative2
    res_g_ab = stats.ttest_ind(a, b, **options_p)
        N          = 50
        a          = array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
    ...75],
       [0.18619301, 0.94437239, 0.7395508 , 0.49045881],
       [0.22741463, 0.25435648, 0.05802916, 0.43441663]])
        b          = array([[0.31179588, 0.69634349, 0.37775184, 0.17960368],
       [0.02467873, 0.06724963, 0.67939277, 0.45369684],
    ...25],
       [0.25868407, 0.84903831, 0.03330463, 0.95898272],
       [0.35536885, 0.35670689, 0.0163285 , 0.18523233]])
        options_p  = {'alternative': 'greater', 'permutations': 500000, 'random_state': 0}
        self       = <scipy.stats.tests.test_stats.Test_ttest_ind_permutations object at 0xc4290d30>
/venv/lib/python3.8/site-packages/scipy/stats/stats.py:5867: in ttest_ind
    res = _permutation_ttest(a, b, permutations=permutations,
        a          = array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
    ...75],
       [0.18619301, 0.94437239, 0.7395508 , 0.49045881],
       [0.22741463, 0.25435648, 0.05802916, 0.43441663]])
        alternative = 'greater'
        axis       = 0
        b          = array([[0.31179588, 0.69634349, 0.37775184, 0.17960368],
       [0.02467873, 0.06724963, 0.67939277, 0.45369684],
    ...25],
       [0.25868407, 0.84903831, 0.03330463, 0.95898272],
       [0.35536885, 0.35670689, 0.0163285 , 0.18523233]])
        cna        = False
        cnb        = False
        contains_nan = False
        equal_var  = True
        nan_policy = 'propagate'
        npa        = 'propagate'
        npb        = 'propagate'
        permutations = 500000
        random_state = 0
/venv/lib/python3.8/site-packages/scipy/stats/stats.py:5987: in _permutation_ttest
    mat_perm, permutations = _data_permutations(mat, n=permutations,
        a          = array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
    ...75],
       [0.18619301, 0.94437239, 0.7395508 , 0.49045881],
       [0.22741463, 0.25435648, 0.05802916, 0.43441663]])
        alternative = 'greater'
        axis       = 0
        b          = array([[0.31179588, 0.69634349, 0.37775184, 0.17960368],
       [0.02467873, 0.06724963, 0.67939277, 0.45369684],
    ...25],
       [0.25868407, 0.84903831, 0.03330463, 0.95898272],
       [0.35536885, 0.35670689, 0.0163285 , 0.18523233]])
        equal_var  = True
        mat        = array([[0.5488135 , 0.4236548 , 0.96366276, 0.56804456, 0.0202184 ,
        0.97861834, 0.11827443, 0.52184832, 0.4561..., 0.39902532, 0.3277204 , 0.16053882, 0.59098417,
        0.57575116, 0.15941446, 0.42403225, 0.95898272, 0.18523233]])
        na         = 50
        nan_policy = 'propagate'
        permutations = 500000
        random_state = RandomState(MT19937) at 0xD7B18E68
        t_stat_observed = array([ 0.78934693, -0.08113535, -0.22878563,  0.17163598])
/venv/lib/python3.8/site-packages/scipy/stats/stats.py:5920: in _data_permutations
    data = data[..., indices]        # generate permutations
E   MemoryError: Unable to allocate array with shape (100, 500000, 4) and data type float64
        axis       = 1
        data       = array([[0.5488135 , 0.4236548 , 0.96366276, 0.56804456, 0.0202184 ,
        0.97861834, 0.11827443, 0.52184832, 0.4561..., 0.39902532, 0.3277204 , 0.16053882, 0.59098417,
        0.57575116, 0.15941446, 0.42403225, 0.95898272, 0.18523233]])
        indices    = array([[26, 18, 42, ..., 46, 15, 94],
       [86, 29, 96, ..., 23, 60, 81],
       [ 2, 64, 58, ..., 73, 26, 83],
       ...,
       [64, 93, 67, ..., 77, 75, 36],
       [47, 48, 24, ..., 37, 93, 10],
       [44, 34, 88, ..., 53, 21, 76]])
        m          = 100
        n          = 500000
        n_max      = 9.332621544394415e+157
        random_state = RandomState(MT19937) at 0xD7B18E68
```

</details>

**Comment by tylerjereddy** [comment]
Thanks, I merged the fix from @mdhaber yesterday here: https://github.com/scipy/scipy/pull/13527

So hopefully this will eventually alleviate whatever issues this may cause you.

**Comment by keewis** [comment]
this seems like it would fix the failing 32bit build jobs, but not the failing 64bit py38 build. Also, it's strange that py38 fails but py37 and py39 don't.

To be clear, I'm talking about the official [scipy wheel repository](https://github.com/MacPython/scipy-wheels), over which I don't have any control.

**Comment by mdhaber** [comment]
@keewis is this still a problem? Should I cut the memory usage in half to see if that fixes it?

**Comment by keewis** [comment]
yes, the [CI](https://dev.azure.com/numpy/numpy/_build?definitionId=9&_a=summary&repositoryFilter=3&branchFilter=3260%2C3260%2C3260%2C3260%2C3260%2C3260%2C3260) is still failing. I think this is the same as MacPython/scipy-wheels#114, but I opened this issue here for increased visibility.

**Comment by djhoese** [comment]
Any updates on this and the state of the failing CI?

**Comment by keewis** [comment]
well, it seems *all* CI jobs are currently failing (since at least Mar 14) because of a build issue with `pythran`. This is being worked on in MacPython/scipy-wheels#116.

Also, it seems that #13661 is planning to fix this issue.

**Comment by tylerjereddy** [comment]
Yeah, we also need to change the `manylinux` version we use to adopt the newer C++ standard I believe. I'll do what I can--I can probably mimic some of what NumPy did when they bumped manylinux versions.

**Comment by rgommers** [comment]
There's new wheels for macOS on https://anaconda.org/scipy-wheels-nightly/scipy/files, and others will appear as we fix more jobs. Working on it ....
