### ISSUE TITLE
DOC: -np.inf as default argument not rendering correctly in DIRECT docstring

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#16385]
There is a minor annoyance in the docstring of the recently added `direct` algorithm:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/40656107/173129273-913f0e6d-5370-463d-ab39-c7f0661abaa2.png">

sphinx cannot correctly parse `-np.inf` . I tried to google the issue but could not find an immediate fix. Maybe a more experienced sphinx user has an idea?

**Comment by WarrenWeckesser** [comment]
Other occurrences of the problem with `-np.inf`:
* https://scipy.github.io/devdocs/reference/generated/scipy.optimize.LinearConstraint.html
* https://scipy.github.io/devdocs/reference/generated/scipy.optimize.Bounds.html

It looks like there are two issues here:

* Sphinx/autodoc evaluates default values, and in the rendered docs, it displays the result of the evaluation, not the original literal text.  In Sphinx 4.0+, this can be disabled with configuration variable `autodoc_preserve_defaults` (see https://github.com/sphinx-doc/sphinx/pull/8771).
* With negative default values, a spurious space is inserted between the minus sign and the first digit.  Examples of this issue that do not involve `-np.inf` include
  * https://scipy.github.io/devdocs/reference/generated/scipy.optimize.dual_annealing.html; see the `accept` parameter;
  * https://scipy.github.io/devdocs/reference/generated/scipy.stats.mstats.hdmedian.html; see the `axis` parameter.

  The same problem shows up in the NumPy docs; see the `axis` parameter in these docstrings:

    * https://numpy.org/doc/stable/reference/generated/numpy.trapz.html
    * https://numpy.org/doc/stable/reference/generated/numpy.unwrap.html

  But not all negative default values result in the spurious space:

    * https://numpy.org/doc/stable/reference/generated/numpy.diff.html

Maybe the numpydoc devs have seen this before: @jarrodmillman, @larsoner, @rossbar, is this a known issue?

**Comment by WarrenWeckesser** [comment]
Another example: the spurious space shows up in the rendering of the `na_sentinel` default value in the Pandas docs for [`pandas.factorize`](https://pandas.pydata.org/docs/reference/api/pandas.factorize.html).

**Comment by WarrenWeckesser** [comment]
I added the "upstream bug" tag.  This is probably a bug in Sphinx itself or in the theme used by SciPy, NumPy and Pandas.

**Comment by tupui** [comment]
If there is nothing we can/should do, then we should close it IMO.

**Comment by dschmitz89** [comment]
> Other occurrences of the problem with `-np.inf`:
> 
> * https://scipy.github.io/devdocs/reference/generated/scipy.optimize.LinearConstraint.html
> * https://scipy.github.io/devdocs/reference/generated/scipy.optimize.Bounds.html
> 
> It looks like there are two issues here:
> 
> * Sphinx/autodoc evaluates default values, and in the rendered docs, it displays the result of the evaluation, not the original literal text.  In Sphinx 4.0+, this can be disabled with configuration variable `autodoc_preserve_defaults` (see [Fix #759: autodoc: Add sphinx.ext.autodoc.preserve_defaults extension sphinx-doc/sphinx#8771](https://github.com/sphinx-doc/sphinx/pull/8771)).

Would adding `autodoc_preserve_defaults = True` to conf.py be enough to fix this?

**Comment by WarrenWeckesser** [comment]
@dschmitz89, it turns out that the problem *is* a bug in Sphinx: https://github.com/sphinx-doc/sphinx/issues/10550

The proposed fix is in https://github.com/sphinx-doc/sphinx/pull/10551

I'll close this issue when that Sphinx pull request is merged, because then we'll have a definitive resolution of the issue: the problem is fixed in Sphinx 5.1.0.

I think the use of `autodoc_preserve_defaults` is a separate issue that would require some discussion and some trial runs to see how it affects the rendered default values throughout the SciPy docs.

**Comment by dschmitz89** [comment]
@WarrenWeckesser : from what I understood, the Sphinx bug will fix the additional space but we would still see `-inf` instead of `-np.inf`. Changing sphinx config can be painful, I agree, maybe @tupui or a seasoned scipy doc expert has an opinion.

**Comment by dschmitz89** [comment]
> @WarrenWeckesser : from what I understood, the Sphinx bug will fix the additional space but we would still see `-inf` instead of `-np.inf`. Changing sphinx config can be painful, I agree, maybe @tupui or the seasoned scipy doc experts have an opinion.

**Comment by AA-Turner** [comment]
`autodoc_preserve_defaults` wouldn't work as it still uses the AST, example reproducer script below. 


```
import shutil
from pathlib import Path

from sphinx.cmd.make_mode import run_make_mode

def write(filename, text): Path(filename).write_text(text, encoding="utf-8")

write("conf.py", '''\
import os, sys
sys.path.insert(0, os.path.abspath(".."))
extensions = ["sphinx.ext.autodoc"]
autodoc_preserve_defaults = True
''')

write("extra_white.py", '''\
def func(axis=-0x1): ...
''')

write("index.rst", '''\
.. autofunction:: extra_white.func
''')

shutil.rmtree("_build", ignore_errors=True)
run_make_mode(["html", ".", "_build", "-T", "-W"])
```

A

**Comment by WarrenWeckesser** [comment]
Thanks @AA-Turner, that makes sense.  So if we used that option in SciPy now we would get `f_min=- np.inf` in the rendered `direct` docstring.

**Comment by tupui** [comment]
I confirmed the spacing issue will be resolved with Sphinx 5.1.0 (see https://github.com/sphinx-doc/sphinx/pull/10551#issuecomment-1156332539).

If the

**Comment by dschmitz89** [comment]
`-inf` instead of `-np.inf` might not be too bad but what if a default argument is some complex class like `scipy.stats.rv_continuous` ?

**Comment by tupui** [comment]
> `-inf` instead of `-np.inf` might not be too bad but what if a default argument is some complex class like `scipy.stats.rv_continuous` ?

Well this should not really happen as it would be a bad design. Default arguments should always be simple things like string, scalars, booleans, None. Anything else would break (e.g. using an empty dict which leads to bugs) and is an anti pattern.

**Comment by WarrenWeckesser** [comment]
Over in the Sphinx repo, https://github.com/sphinx-doc/sphinx/pull/10551 has been merged and the fix for the extra space will be in Sphinx 5.1.0. 

I'm closing this issue, because I think the extra space was the main problem. Of course, our web site won't reflect this change until we build it with Sphinx 5.1, so if anyone is even more conservative about closing this than I am and thinks it should remain open until our web site is actually fixed, feel free to reopen the issue.

I think the question of enabling `autodoc_preserve_defaults` should be discussed in a new issue.

**Comment by WarrenWeckesser** [comment]
>  But the next dev on master will have it, and also 1.9 since we don't have upper pins for Sphinx. So all good.

The fix will be in Sphinx 5.1.0, which is not released yet.  It looks like Sphinx has a [release cadence of about two months](https://pypi.org/project/Sphinx/5.0.2/#history), and 5.0.0 was released May 29, so I wouldn't expect 5.1.0 to be released until the end of July.

**Comment by WarrenWeckesser** [comment]
*Status update*: It looks like the 1.9.0 docs were built with Sphinx <5.1.0, so they still have the spurious space, e.g. https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.direct.html.

A newer version of Sphinx is used to build the development version of the docs, so in those the problem is fixed: https://scipy.github.io/devdocs/reference/generated/scipy.optimize.direct.html

**Comment by tupui** [comment]
Maybe we should just bump the minimal version for Sphinx.
