### ISSUE TITLE
Cirrus CI job `musllinux_amd64_test` is consistently failing

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#17475]
According to the log, `/usr/bin/pythran` is found, but the following error is reported:

```
scipy/meson.build:74:2: ERROR: Command "/tmp/cirrus-ci-build/python -c import os; os.chdir(".."); import pythran; print(os.path.dirname(pythran.__file__));" failed with status 1.
```

<details>
<summary>Full log</summary>

```
python dev.py build
💻  meson setup /tmp/cirrus-ci-build/build --prefix 
/tmp/cirrus-ci-build/build-install
The Meson build system
Version: 0.64.1
Source dir: /tmp/cirrus-ci-build
Build dir: /tmp/cirrus-ci-build/build
Build type: native build
Project name: SciPy
Project version: 1.10.0.dev0
C compiler for the host machine: cc (gcc 12.2.1 "cc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924")
C linker for the host machine: cc ld.bfd 2.39
C++ compiler for the host machine: c++ (gcc 12.2.1 "c++ (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924")
C++ linker for the host machine: c++ ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C supports arguments -Wno-unused-function: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
Library m found: YES
Fortran compiler for the host machine: gfortran (gcc 12.2.1 "GNU Fortran (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924")
Fortran linker for the host machine: gfortran ld.bfd 2.39
Compiler for Fortran supports arguments -Wno-conversion: YES 
Checking if "-Wl,--version-script" : links: YES 
Program cython found: YES (/usr/bin/cython)
Program python3 found: YES (/tmp/cirrus-ci-build/python)
Found pkg-config: /usr/bin/pkg-config (1.9.3)
Program pythran found: YES (/usr/bin/pythran)
Run-time dependency threads found: YES
Library npymath found: YES
Library npyrandom found: YES

scipy/meson.build:74:2: ERROR: Command "/tmp/cirrus-ci-build/python -c import os; os.chdir(".."); import pythran; print(os.path.dirname(pythran.__file__));" failed with status 1.

A full log can be found at /tmp/cirrus-ci-build/build/meson-logs/meson-log.txt
Meson build setup failed!
```

</details>

Ping @andyfaff.

**Comment by andyfaff** [comment]
@rgommers might have a clearer idea.

**Comment by rgommers** [comment]
Hmm, not sure what is going on there. `pythran` has not had a release in 2 months. `meson` just did `0.64.1`, so that was the most likely suspect - but I browsed through all commits and didn't see anything that immediately jumped out. 

This would be easier if we could access `build/meson-logs/meson-log.txt` to see what the actual problem is. That is going to come up more often perhaps, so I'll have a look at how to approach it. Pushing a debug commit each time it happens is less than ideal.

**Comment by ideasrule** [comment]
I also see this for my pull request (#17472).

**Comment by andyfaff** [comment]
The relevant log part for this is:
```
--- stderr ---
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/pythran/__init__.py", line 41, in <module>
    from pythran.config import get_include
  File "/usr/lib/python3.10/site-packages/pythran/config.py", line 8, in <module>
    import numpy.distutils.system_info as numpy_sys
  File "/usr/lib/python3.10/site-packages/numpy/distutils/__init__.py", line 26, in <module>
    from . import ccompiler
  File "/usr/lib/python3.10/site-packages/numpy/distutils/ccompiler.py", line 20, in <module>
    from numpy.distutils import log
  File "/usr/lib/python3.10/site-packages/numpy/distutils/log.py", line 4, in <module>
    from distutils.log import Log as old_Log
ImportError: cannot import name 'Log' from 'distutils.log' (/usr/lib/python3.10/site-packages/setuptools/_distutils/log.py)
```
So it's related to https://github.com/numpy/numpy/issues/22623.
We can get around this by pinning `setuptools`. However, it's really an upstream issue as well:

1. numpy got broken by setuptools
2. The type of system_info that pythran is getting shouldn't have to come from `numpy.distutils`, it should be made available from somewhere else in numpy, if numpy.distutils is going to be deprecated.

**Comment by andyfaff** [comment]
FWIW I debugged in an Alpine VM using docker on my M1 mac:

`docker run --rm -it -v $PWD:/io  --platform linux/amd64 alpine`

**Comment by WarrenWeckesser** [comment]
Thanks @andyfaff.

It is a bit worrying that after the fix was merged, the job `musllinux_amd64_test` that runs on the main branch had a seg. fault in a LAPACK call in `linalg`.  But in a subsequent commit to main, the job passed.  Go figure.

**Comment by andyfaff** [comment]
The only thing I changed was pin `setuptools`!

**Comment by rgommers** [comment]
I opened a Pythran PR to fix the cause of that issue here, so this doesn't happen again the next time `setuptools` decides to rip out something that `numpy.distutils` depends on: https://github.com/serge-sans-paille/pythran/pull/2049.

Thinking about the `meson-log.txt` issue some more, I've concluded that it isn't much of a problem. The failing line is still shows in the CI log, and most of the time that is enough. `meson-log.txt` contains 1000+ lines of detailed config checks, so echoing that to the CI log on every failure is probably not going to be too helpful on average.

**Comment by rgommers** [comment]
I just saw this job fail again - it looks like Cirrus CI does the same as CircleCI: not merging with `main` before running tests. We fixed that for CircleCI in gh-10211. @andyfaff did you notice this before, and do you think we should copy the CircleCI solution from gh-10211 for it?

**Comment by andyfaff** [comment]
I think the thing to do is a custom clone command, https://cirrus-ci.org/guide/tips-and-tricks/#custom-clone-command. However, it seems a bit silly to me that on a PR the default isn't to merge `main` first.
