### ISSUE TITLE
eig() returns only two eigenvectores similart to MATLAB and the rest do not make sense when compared with MATLAB eig()

### ISSUE THREAD

**Issue by laniakea** [scipy/scipy#18260]
This is what I'm comparing Scipy with:

https://www.mathworks.com/matlabcentral/fileexchange/58967-singular-spectrum-analysis-beginners-guide

In the Matlab link, please go to the "Examples" tab and you'll see the code I've embedded here in Matlab and see the plots.

This is how Singular Spectrum Analysis is done and I need to get the eigenvectors of the decomposition. The 1st and 2nd eigenvectors are similar (acceptable) but from 3rd on, they do not make sense. Am I missing something?

Here is the code I'm running:

```python
M = 30        # window length = embedding dimension
N = 200       # length of generated time series
T = 22        # period length of sine function
stdnoise = 1  # noise-to-signal ratio

t = np.arange(0,N)
X = np.sin(2*np.pi*t/T)
noise = np.random.normal(0, 1, size=N)

X = X+noise
X = X-np.mean(X)
X = X/np.std(X)

plt.plot(t, X)

Y = np.zeros((N-M+1,M))

for m in range(1,M):
  Y[:,m] = X[m-1:(N-M+1)+m-1]

Cemb = np.dot(Y.T,Y)/(N-M+1)
Lambda,RHO = la.eig(Cemb)

idx = Lambda.argsort()[::-1]
Lambda = [idx]
RHO = RHO[:,idx]

fig, ax = plt.subplots(figsize=(16,1))
ax.plot(RHO[:,0])
ax.plot(RHO[:,1])

fig, ax = plt.subplots(figsize=(16,1))
ax.plot(RHO[:,2])
ax.plot(RHO[:,3])
```

The problem is the periodics/cycles/frequncy of RHO[:,0],RHO[:,1] matches the MATLAB code but RHO[:,2],RHO[:,3] etc. don't.
May be I missed something but this result is odd.

Thanks.

**Comment by ilayn** [comment]
Could you please simplify example to eig only and demonstrate the numbers that are not mismatching? 

Note that matlab scipy and any other major linalg software all use the same LAPACK engine. And eigenvectors are not unique; you can expect sign changes.

**Comment by laniakea** [comment]
No further simplification is possible (makes sense).
Here is some explanation: the stochastic time series is simply white noise.
When the eigenvalue/eigenvectors (eigenpairs from now on) are obtains, they are not sorted. They must be sorted first.
After sorting  the eigenpairs accordingly, I map the time series along the eigenpairs. The 1st and 2nd mappings of the time series simlar to Matlab plots, but after the 2nd, the rest the mapping plots are not complying even if I use eigh(). Note that it doesn't matter if the eigenpairs are different, but the mappings must be identical.

**Comment by mdhaber** [comment]
It looks to me like SciPy produces a valid eigendecomposition here.
```python3
np.testing.assert_allclose(RHO @ np.diag(Lambda) @ RHO.T, Cemb)  # passes
np.testing.assert_allclose(RHO @ RHO.T, np.eye(len(Cemb)), atol=1e-12)  # passes
```

**Comment by laniakea** [comment]
Did you plot the time series mappings @mdhaber?

**Comment by ilayn** [comment]
> No further simplification is possible (makes sense). Here is some explanation: the stochastic time series is simply white noise... 


Sorry but we can't troubleshoot your script. If there is no further details about the issue then you have to get the details yourself. Please get rid of the extra scipt and make only about eig(). Then please show matlab and scipy difference. Otherwise this is a no issue.

**Comment by laniakea** [comment]
There is no "extra" script. The first few lines are to generate a white noise process in order to verify the correctness of the eig().
I also posted the link to the matlab documentation where it shows how the plots must look like after sorting and multiplication.

**Comment by josef-pkt** [comment]
I think the indexing in translating from matlab might be wrong.

Also the noise is large for a short time series. My guess is that matlab docs choose a "nice" seed.
Only the first two eigenvalues are large, the others are pretty close to each other and with the large noise those eigenvectors might not be very replicable.

So the problem is in the application and not in linalg definitions.

**Comment by rkern** [comment]
There's definitely a bug in the indexing here:

```python
for m in range(1,M):
  Y[:,m] = X[m-1:(N-M+1)+m-1]
```

That should be looping over `range(M)`, with appropriate adjustments to the RHS to match.

I am going to close this. We've verified that we return valid eigendecompositions in this context. Debugging the rest of the script is out of scope for this forum.

**Comment by josef-pkt** [comment]
I had fixed that indexing bug in the version that I tried out.
But even with some changes to the code to bring it closer to the matlab code, I get the "expected" picture only every once in a while for some random runs.

![image](https://user-images.githubusercontent.com/440735/230741101-8aef3f07-8e88-4a4d-bce8-ed2b14ab19e1.png)


The only possible difference I could think of is whether matlab uses complex numbers differently.
But I don't understand how eigenvalues and eigenvectors in complex cases are supposed to behave.

**Comment by laniakea** [comment]
@rkern range(M) will resutl in negative index in X[m-1: ... ] it must start from 1 in python.

**Comment by laniakea** [comment]
@josef-pkt that plot is acceptable from point of view. What version are you working with and can you share your code please?

**Comment by josef-pkt** [comment]
for m in range(1,M+1):
    Y[:,m-1] = X[m-1:(N-M+1)+m-1]


linalg question:

Is this
Lambda,RHO = la.eigh(Cemb.astype(np.complex128))
the same as keeping it real?

**Comment by rkern** [comment]
> range(M) will resutl in negative index in X[m-1: ... ] it must start from 1 in python.

That's why I said you need to change the right-hand-side accordingly.

```python
for m in range(M):
  Y[:,m] = X[m:(N-M+1)+m]
```

> But even with some changes to the code to bring it closer to the matlab code, I get the "expected" picture only every once in a while for some random runs.

Because the noise level is very high, the results are _very_ dependent on the random noise. Even with the fixed code, you are comparing the final results of the same algorithm done on two different sets of data. That is not evidence that the Python version of the algorithm is doing something wrong.

**Comment by josef-pkt** [comment]
this is the version I have that can reproduce the 3rd and 4th eigenvector sometimes

noise is only 0.5

```
M = 30  #*3      # window length = embedding dimension
N = 200 #*6      # length of generated time series
T = 22        # period length of sine function
stdnoise = 0.5  # noise-to-signal ratio

t = np.arange(0,N) + 1
X = np.sin(2*np.pi*t/T)
noise = stdnoise * np.random.normal(0, 1, size=N)

X = X+noise
X = X-np.mean(X)
X = X/np.std(X)

plt.plot(t, X)
# As seen, the results are identical to MATLAB's page.

# Here is the rest:

Y = np.zeros((N-M+1,M))

for m in range(1,M+1):
    Y[:,m-1] = X[m-1:(N-M+1)+m-1]

Cemb = np.dot(Y.T,Y)/(N-M+1)
Lambda,RHO = la.eigh(Cemb.astype(np.complex128))
sort_idx = np.argsort(Lambda)[::-1]
RHO = RHO[:, sort_idx]
PC = np.dot(Y,RHO)
fig, ax = plt.subplots(figsize=(16,1))
ax.plot(RHO[:,0])
ax.plot(RHO[:,1])


fig, ax = plt.subplots(figsize=(16,1))
ax.plot(RHO[:,2])
ax.plot(RHO[:,3])
```

**Comment by ilayn** [comment]
Like I mentioned, you are trying to troubleshoot an algorithm by its output. That's not going to get any easier until you break it down to only, and only the eig part to start questioning eig output. What we need is, 

- an input array, 
- result of matlab's eig command
- result of scipy's eig command 

and **only then** you can claim the output doesn't make any sense. The rest of the problem we don't have any bandwidth to investigate for you. Stackoverflow or any stackexchange network is a better source for this. 

Plus I can spot a common trouble point when translating matlab code is the sorting 

```python
>>> L = np.array([-1, -2, -2-4j, -1-1j, 3, -2+4j, -1+1j])
>>> L[L.argsort()]
array([-2.-4.j, -2.+0.j, -2.+4.j, -1.-1.j, -1.+0.j, -1.+1.j,  3.+0.j])
```

So if you are pairing complex modes then you are not pairing them properly.

**Comment by laniakea** [comment]
@rkern the indexing is not a problem. I believe you closed it too realy.

**Comment by laniakea** [comment]
@ilayn When I sort the eigenvalues, they are not properly sorted. I'm doing this by plottting the eigenvalues (and I also fixed the index typo).

`idx = Lambda.argsort()[::-1]
RHO = RHO[:,idx]
fig, ax = plt.subplots(figsize=(8,2))
ax.plot(Lambda)`

This doesn't produce the right eigenvalue plot. They must be descending.

**Comment by rkern** [comment]
The indexing is definitely a problem. Look at the contents of `Y[:, 0]`.

You haven't actually sorted `Lambda` with that code. Use `Lambda = Lambda[idx]` to apply the sorting.

But nonetheless, you can fix the Python code to be perfect. You will still not get the same results as the MATLAB because they are operating on different random noise. The results that are plotted are strongly dependent on that noise.

**Comment by rkern** [comment]
> So if you are pairing complex modes then you are not pairing them properly.

It's fine in this case, actually, since `Cemb` is positive-definite. The imaginary components are all exactly 0. But yes, doing `Lambda = Lambda.real` before anything else would be good defensive practice.

**Comment by rkern** [comment]
@laniakea If you want us to reopen this, you will have to save `Cemb`, `Lambda`, and `RHO` from the MATLAB code, then load `Cemb` in Python, run `scip.linalg.eig(Cemb)` and show the `Lambda` and `RHO`s that you get from that. All of the other details of your code are introducing many difference to `Cemb` that make the final plots not comparable and thus not evidence of a problem with `scipy.linalg.eig()`.

**Comment by laniakea** [comment]
> The indexing is definitely a problem. Look at the contents of `Y[:, 0]`.
> 
> You haven't actually sorted `Lambda` with that code. Use `Lambda = Lambda[idx]` to apply the sorting.
> 
> But nonetheless, you can fix the Python code to be perfect. You will still not get the same results as the MATLAB because they are operating on different random noise. The results that are plotted are strongly dependent on that noise.

@rkern first of all, I fixed the index problem in the code (see the original post one more time).
second, since the eigenvalue plots are identical, the eign spectrum must behave identical.

So based on the above, unless if the code is correct, the you are wrong. 

To add, It is not data dependent.

**Comment by laniakea** [comment]
> > So if you are pairing complex modes then you are not pairing them properly.
> 
> It's fine in this case, actually, since `Cemb` is positive-definite. The imaginary components are all exactly 0. But yes, doing `Lambda = Lambda.real` before anything else would be good defensive practice.

The restuls must not be imaginary when doing SSA.

**Comment by laniakea** [comment]
> @laniakea If you want us to reopen this, you will have to save `Cemb`, `Lambda`, and `RHO` from the MATLAB code, then load `Cemb` in Python, run `scip.linalg.eig(Cemb)` and show the `Lambda` and `RHO`s that you get from that. All of the other details of your code are introducing many difference to `Cemb` that make the final plots not comparable and thus not evidence of a problem with `scipy.linalg.eig()`.

I don't have access to Matlab unfortunately. But from the plots my judgement is what I posted.

**Comment by laniakea** [comment]
@rkern At this stage it doesn't matter to me. This is defenatly a weakness and it is upto your team to enhance your work. My task was to let you know.

You can clearly see the eigenvalue plots and compare them with the one in Matlabs documentation page.  I don't see a reason to go throught so much trouble to prove the obvious.

**Comment by laniakea** [comment]
This code verifies the Y values:
`M = 30        # window length = embedding dimension
N = 200       # length of generated time series
T = 22        # period length of sine function
stdnoise = 1  # noise-to-signal ratio

t = np.arange(0,N)
X = np.sin(2*np.pi*t/T)
noise = np.random.normal(0, 1, size=N)

X = X+noise
X = X-np.mean(X)
X = X/np.std(X)

plt.plot(t, X)

Y = np.zeros((N-M+1,M))

for m in range(1,M):
  Y[:,m-1] = X[m-1:(N-M+1)+m-1]

print(Y[:,0] == X[0:(N-M+1)])`

**Comment by rkern** [comment]
> To add, this analysis is not data dependent, and it MUST come up with identical (close enough) restuls as you see in the matlab documentation page. To assure you that it is identical, check the eigenvalue plots and compare them. They are identical (almost...).

It's quite data dependent. The noise ratio is quite high. You can repeat the analysis over and over again with the different random draws and you will get qualitatively different results, especially for the eigenvectors after the first two. You will get similar _shapes_ of the eigenvalue spectrum, but the actual values change a fair bit (e.g. the largest eigenvalue has a standard deviation about ~0.6). The first two are largely driven by the underlying sinusoidal signal but for the smaller eigenvalues, they are mostly reflecting features of the noise. "Almost identical" is not "actually identical".

> I don't have access to Matlab unfortunately. But from the plots my judgement is what I posted. Eigenplots and periodics must definitively comply with matlab plots.

I'm sorry, but you haven't presented any convincing evidence of this.

You can try installing Octave, the free MATLAB clone and running the MATLAB code there. Try multiple times and look at the intrinsic variation of the random data.

**Comment by laniakea** [comment]
I highly doubt that your statement is correct. If it is, why eigenvalue plots are identical?

**Comment by rkern** [comment]
> for m in range(1,M):
> Y[:,m-1] = X[m-1:(N-M+1)+m-1]

In order to match the MATLAB code, this would have to be `range(1, M+1)`. The MATLAB `(1:M)` translates to `range(1, M+1)`. Check `Y[:, -1]` to confirm.

**Comment by rkern** [comment]
> I highly doubt that your statement is correct. If it is, why eigenvalue plots are identical?

They are not _identical_. They have _similar_ shapes. The actual numbers vary a fair bit with each run.

**Comment by laniakea** [comment]
> > I highly doubt that your statement is correct. If it is, why eigenvalue plots are identical?
> 
> They are not _identical_. They have _similar_ shapes. The actual numbers vary a fair bit with each run.

They are not. This code is to prove:
`M = 30        # window length = embedding dimension
N = 200       # length of generated time series
T = 22        # period length of sine function
stdnoise = 1  # noise-to-signal ratio

t = np.arange(0,N)
X = np.sin(2*np.pi*t/T)
noise = np.random.normal(0, 1, size=N)

X = X+noise
X = X-np.mean(X)
X = X/np.std(X)

plt.plot(t, X)

Y = np.zeros((N-M+1,M))

for m in range(1, M+1):
  Y[:,m-1] = X[m-1:(N-M+1)+m-1]

Cemb = np.dot(Y.T,Y)/(N-M+1)
Lambda,RHO = la.eigh(Cemb)

print(Lambda[-1]/Lambda[-2])`

The ratio is what matters not the numbers. Run this code many times and see how the ratio remains close.

**Comment by rkern** [comment]
For the two largest eigenvalues, sure, it's close, but still variable. For the rest, the ratio varies much more. Here are 100 eigenspectra, normalized by the largest eigenvalue.

![download](https://user-images.githubusercontent.com/46135/230777579-6475d8cc-40da-4e26-9d11-837cbff92ffb.png)

**Comment by laniakea** [comment]
That proved what I just said. The eigenpairs represent variance along various axis. And they exponentially decrease in scale. The plot you just made is inline with what I said.

Now the 3rd and 4rth eigenpairs seems to be very close, that means they have the same priodics/cycles (platea).

Now the argsort doesn't work for me.  I can't sort the eigenpairs, it seems it is a typically known issue!

`M = 30        # window length = embedding dimension
N = 200       # length of generated time series
T = 22        # period length of sine function
stdnoise = 1  # noise-to-signal ratio

t = np.arange(0,N)
X = np.sin(2*np.pi*t/T)
noise = np.random.normal(0, 1, size=N)

X = X+noise
X = X-np.mean(X)
X = X/np.std(X)

plt.plot(t, X)

Y = np.zeros((N-M+1,M))

for m in range(1, M+1):
  Y[:,m-1] = X[m-1:(N-M+1)+m-1]

Cemb = np.dot(Y.T,Y)/(N-M+1)
Lambda,RHO = la.eig(Cemb)
idx = Lambda.argsort()[::-1]
RHO = RHO[:,idx]

fig, ax = plt.subplots(figsize=(8,2))
ax.plot(Lambda)`

**Comment by rkern** [comment]
You can use [MATLAB Online](https://www.mathworks.com/products/matlab-online.html) for free to confirm the variability of the MATLAB code as well. I just copied the MATLAB code and got the following, which is qualitatively different from what's plotted in the tutorial, but in line with the results I've seen from the Python.

![Eigenvectors RHO and eigenvalues LAMBDA](https://user-images.githubusercontent.com/46135/230778012-e2497e39-cf9f-44ac-bf65-ab6a3959702d.png)

Here's another:

![Eigenvectors RHO and eigenvalues LAMBDA 2](https://user-images.githubusercontent.com/46135/230778227-eddb13ef-c78c-438d-859c-1f72fbe855f6.png)

**Comment by laniakea** [comment]
Thanks for your time and validation and thanks for the online Matlab link (I wasn't aware of it). I actually learned more than few lessons.

**Comment by rkern** [comment]
To close this out, I [saved a `.mat` file](https://github.com/scipy/scipy/files/11185683/matlab.zip) with `Cemb`, `LAMBDA`, and `RHO` from one run of the MATLAB script. We can then confirm that the results are identical up to numerical precision of the eigenvalues and the sign of the eigenvectors, which is an expected variation.

```python
from scipy import io
from scipy import linalg as la

m = io.loadmat('matlab.mat')

Lambda, RHO = la.eig(m['Cemb'])
Lambda = Lambda.real
idx = Lambda.argsort()[::-1]
Lambda = Lambda[idx]
RHO = RHO[:, idx]
print(Lambda - m['LAMBDA'].T)
print(RHO / m['RHO'])
```
<details><summary>Results</summary>

```
[[-8.88178420e-16 -3.99680289e-15  2.66453526e-15 -3.77475828e-15
  -2.88657986e-15 -3.55271368e-15  1.11022302e-15  1.11022302e-15
  -1.11022302e-16 -5.55111512e-16 -5.55111512e-16  1.11022302e-15
   0.00000000e+00 -2.22044605e-16 -3.33066907e-16 -1.11022302e-16
  -6.66133815e-16 -1.22124533e-15  4.44089210e-16  4.44089210e-16
  -4.44089210e-16 -6.66133815e-16  5.55111512e-16 -1.11022302e-15
   3.88578059e-16  0.00000000e+00  6.66133815e-16  2.77555756e-16
  -1.66533454e-16  3.33066907e-16]]
[[ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1.  1.  1. -1.  1. -1. -1.
  -1.  1. -1. -1.  1.  1. -1. -1. -1. -1.  1.  1.]]
```
</details>
