### ISSUE TITLE
BUG: Bad result (broadcasting ?) for binom.ppf and q=1, when all arguments have size > 1

### ISSUE THREAD

**Issue by arnaud-ma** [scipy/scipy#18919]
### Describe your issue.

Normally, binom.ppf should return the upper value (the n parameter) when q = 1, for example:
```python3
>>>stats.binom.ppf(q=1, n=10, p=0.5)
10.0
```

but when the arguments are no longer scalars (at least for 'n' and for 'q'), we don't get the expected result : 
```python3
>>>q = [0.5, 1]
>>>n = [10, 11]
>>>p = [0, 0.5]
>>>stats._boost.binom.ppf(q, n, p) # expected result
array([ 0., 11.])
>>>stats.binom.ppf(q, n, p) # but...
array([ 0., 10.])
```

By doing several tests with higher dimensions, it seems that the bug occurs for each q = 1, and instead of taking its correct value, it takes the next value of n.flatten()
```python3
>>> q = [[0.5, 1.0, 0.5],
...      [1.0, 0.5, 1.0],
...      [0.5, 1.0, 0.5]]
>>> n = [[45, 46, 47],
...      [48, 49, 50],
...      [51, 52, 53]]
>>> p = 0.5
>>> stats._boost._binom_ppf(q, n, p) 
array([[22., 46., 23.],
       [48., 24., 50.],
       [25., 52., 26.]])
>>> stats.binom.ppf(q, n, p) 
array([[22., 45., 23.],
       [46., 24., 47.],
       [25., 48., 26.]])
>>> n = [45, 46, 47]
>>> stats.binom.ppf(q, n, p)
array([[22., 45., 23.],
       [46., 23., 47.],
       [22., 45., 23.]])
```

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import binom, _boost

q = [[0.5, 1.0, 0.5],
     [1.0, 0.5, 1.0],
     [0.5, 1.0, 0.5]]

n = [[45, 46, 47],
     [48, 49, 50],
     [51, 52, 53]]

p = 0.5

result1 = _boost._binom_ppf(q, n, p)
result2 = np.vectorize(binom.ppf)(q, n, p)

bad_result = binom.ppf(q, n, p)

print(f"{(result1 == result2).all()=}") # True
print(f"{(result1 == bad_result).all()=}") # False
```

### Error message

```shell
No error message
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.25.1 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-dqdt9tl_\overlay\Lib\site-packages/pythran 
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-qsxtw44z\cp311-win_amd64\build\venv\Scripts\python.exe
  version: '3.11'
```

**Comment by mdhaber** [comment]
Impressive. Looks like this has been a bug since at least SciPy 1.0.

```
(scipy10) C:\Users\matth>python
Python 2.7.15 |Anaconda, Inc.| (default, Nov 13 2018, 17:33:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.0.1'
>>> from scipy import stats
>>> stats.binom.ppf([0.5, 1], [11, 11], [1, 1])
array([11., 11.])
>>> stats.binom.ppf([0.5, 1], [10, 11], [1, 1])
array([10., 10.])
>>> stats.binom.ppf([0.5, 1], [9, 11], [1, 1])
array([9., 9.])
>>> stats.binom.ppf([0.5, 1], [8, 11], [1, 1])
array([8., 8.])
```

We'll fix this as part of gh-15928.

**Comment by mdhaber** [comment]
This was resolved by gh-22312, available in SciPy 1.16.

```python3
import numpy as np
from scipy import stats
from scipy.special._ufuncs import _binom_ppf

q = [[0.5, 1.0, 0.5],
     [1.0, 0.5, 1.0],
     [0.5, 1.0, 0.5]]

n = [[45, 46, 47],
     [48, 49, 50],
     [51, 52, 53]]

p = 0.5

X = stats.Binomial(n=n, p=p)

result1 = _binom_ppf(q, n, p)
result2 = X.icdf(q)
np.testing.assert_equal(result1, result2)
```

I don't foresee a fix for `rv_discrete.ppf` because 1) there is already a better option and 2) the `rv_discrete` infrastructure is quite challenging to work on - fix something for someone, break something else for someone else. Happy to re-open if there are two maintainers willing to work on this (one to write, one to review), though.

**Comment by WarrenWeckesser** [comment]
I don't think this issue should be closed.  Providing a work-around is useful, but it is not (in general) a justification for marking bugs in the existing public API as "won't fix".  There is a bug in `binom.ppf`, and that is still a supported public API.

And to be clear, the bug still exists in the main development branch:

```
In [30]: import scipy

In [31]: scipy.__version__
Out[31]: '1.17.0.dev0+git20250929.434fc55'
```
Scalar calculations:
```
In [32]: binom.ppf(0.5, n=9, p=0.5)
Out[32]: np.float64(4.0)

In [33]: binom.ppf(1.0, n=10, p=0.5)
Out[33]: np.float64(10.0)
```
Broadcast result should match those scalar results:
```
In [34]: binom.ppf([0.5, 1.0], n=[9, 10], p=0.5)
Out[34]: array([4., 9.])
```

**Comment by arnaud-ma** [comment]
Maybe a compromise would be to add a warning with something like "The old API may cause bugs or unexpected behavior. Please use the new API instead". I also think that as long as it remains part of the public API without any clarification, it should still be considered a bug.

**Comment by mdhaber** [comment]
Excellent : ) I thought that maybe closing this would draw the attention it needed. Please feel free to submit a PR @WarrenWeckesser. I'd be willing to review. *Never mind, I just went ahead and fixed it.*
