### ISSUE TITLE
BUG: input's `device` isn't inherited for newly created `xp.asarrays`

### ISSUE THREAD

**Issue by betatim** [scipy/scipy#21736]
### Describe your issue.

We just finished adding ["multi device" support](https://github.com/data-apis/array-api-strict/pull/59) to `array-api-strict` and while test driving it by running the scikit-learn test suite I found that (for example)

https://github.com/scipy/scipy/blob/2d5e63d0c5bc425cb23f3614efe5e6101e6c37f9/scipy/special/_support_alternative_backends.py#L77

creates a new array to pass as argument to `xp.where` but it does not set the device. This means that if you pass in an array on a device that isn't the default device, the newly created array will be on a different device. Which, I think, means you can't combine it with the original array. Basically, all arguments to `xp.where` have to be on the same device.

I think the fix is to make sure to pass `device=...` to `asarray()` calls. What do you think?

### Reproducing Code Example

```python
import scipy.special
import array_api_strict # the very latest version

x = array_api_strict.asarray([1.,2,3], device=array_api_strict.Device("device1"))

scipy.special.xlogy(x, x)
```

### Error message

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 1
----> 1 scipy.special.xlogy(x, x)

File ~/miniconda/envs/sklearn-py3.10-v2/lib/python3.10/site-packages/scipy/special/_support_alternative_backends.py:117, in support_alternative_backends.<locals>.wrapped(*args, **kwargs)
    115 xp = array_namespace(*args[:n_array_args])
    116 f = get_array_special_func(f_name, xp, n_array_args)
--> 117 return f(*args, **kwargs)

File ~/miniconda/envs/sklearn-py3.10-v2/lib/python3.10/site-packages/scipy/special/_support_alternative_backends.py:80, in _xlogy.<locals>.__xlogy(x, y, xp)
     78 with np.errstate(divide='ignore', invalid='ignore'):
     79     temp = x * xp.log(y)
---> 80 return xp.where(x == 0., xp.asarray(0., dtype=temp.dtype), temp)

File ~/git/array-api-strict/array_api_strict/_searching_functions.py:85, in where(condition, x1, x2)
     82 _result_type(x1.dtype, x2.dtype)
     84 if len({a.device for a in (condition, x1, x2)}) > 1:
---> 85     raise ValueError("where inputs must all be on the same device")
     87 x1, x2 = Array._normalize_two_args(x1, x2)
     88 return Array._new(np.where(condition._array, x1._array, x2._array), device=x1.device)

ValueError: where inputs must all be on the same device
```

### SciPy/NumPy/Python version and system information

```shell
1.14.0 2.0.0 sys.version_info(major=3, minor=10, micro=13, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Users/thead/miniconda/envs/sklearn-py3.10-v2/include
    lib directory: /Users/thead/miniconda/envs/sklearn-py3.10-v2/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /Users/thead/miniconda/envs/sklearn-py3.10-v2/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /Users/thead/miniconda/envs/sklearn-py3.10-v2/include
    lib directory: /Users/thead/miniconda/envs/sklearn-py3.10-v2/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /Users/thead/miniconda/envs/sklearn-py3.10-v2/lib/pkgconfig
    version: 3.9.0
  pybind11:
    detection method: pkgconfig
    include directory: /Users/thead/miniconda/envs/sklearn-py3.10-v2/include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /Users/thead/miniconda/envs/sklearn-py3.10-v2/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1719280596793/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/thead/miniconda/envs/sklearn-py3.10-v2=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include,
      -mmacosx-version-min=11.0, -mmacosx-version-min=11.0
    commands: arm64-apple-darwin20.0.0-clang
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/thead/miniconda/envs/sklearn-py3.10-v2/lib,
      -L/Users/thead/miniconda/envs/sklearn-py3.10-v2/lib, -ftree-vectorize, -fPIC,
      -fstack-protector-strong, -O2, -pipe, -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include,
      -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1719280596793/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/thead/miniconda/envs/sklearn-py3.10-v2=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include,
      -mmacosx-version-min=11.0, -mmacosx-version-min=11.0
    name: clang
    version: 16.0.6
  c++:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++,
      -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include,
      -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1719280596793/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/thead/miniconda/envs/sklearn-py3.10-v2=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include,
      -mmacosx-version-min=11.0, -mmacosx-version-min=11.0
    commands: arm64-apple-darwin20.0.0-clang++
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/thead/miniconda/envs/sklearn-py3.10-v2/lib,
      -L/Users/thead/miniconda/envs/sklearn-py3.10-v2/lib, -ftree-vectorize, -fPIC,
      -fstack-protector-strong, -O2, -pipe, -stdlib=libc++, -fvisibility-inlines-hidden,
      -fmessage-length=0, -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include,
      -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1719280596793/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/thead/miniconda/envs/sklearn-py3.10-v2=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include,
      -mmacosx-version-min=11.0, -mmacosx-version-min=11.0
    name: clang
    version: 16.0.6
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    args: -march=armv8.3-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe,
      -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1719280596793/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/thead/miniconda/envs/sklearn-py3.10-v2=/usr/local/src/conda-prefix
    commands: /Users/runner/miniforge3/conda-bld/scipy-split_1719280596793/_build_env/bin/arm64-apple-darwin20.0.0-gfortran
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/thead/miniconda/envs/sklearn-py3.10-v2/lib,
      -L/Users/thead/miniconda/envs/sklearn-py3.10-v2/lib, -march=armv8.3-a, -ftree-vectorize,
      -fPIC, -fno-stack-protector, -O2, -pipe, -isystem, /Users/thead/miniconda/envs/sklearn-py3.10-v2/include,
      -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1719280596793/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/thead/miniconda/envs/sklearn-py3.10-v2=/usr/local/src/conda-prefix
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../_build_env/venv/lib/python3.10/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
  cross-compiled: true
  host:
    cpu: arm64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /Users/thead/miniconda/envs/sklearn-py3.10-v2/bin/python
  version: '3.10'
```

**Comment by lucascolley** [comment]
Yeah, we'll want to match the sk-learn PR and catch all of these issues at once.

**Comment by mdhaber** [comment]
> (there are probably other instances of this as well, I've not tried to look for them)

Yeah, like every test with a hard-coded reference value. Sounds like a lot of fun.

**Comment by betatim** [comment]
I agree that this kind of thing is a big reason to support scalars. It is a trap everyone will fall into and it is mega tedious to fix it/do it right.

I'm wondering how long it will take for the change to be accepted into the standard and then get implemented in the various libs/array-api-compat. Compared to how long it'll take to add (and then remove) it from scipy.

**Comment by lesteve** [comment]
I am pretty sure this was fixed in scipy 1.16. I just tried with scipy 1.16.0 and the snippet runs fine (with 1.15.2 it fails as in the original post)

With scipy 1.16.0:
```py
In [1]: import scipy.special
   ...: import array_api_strict # the very latest version
   ...: 
   ...: x = array_api_strict.asarray([1.,2,3], device=array_api_strict.Device("device1"))
   ...: 
   ...: scipy.special.xlogy(x, x)
Out[1]: 
Array([0.        ,
       1.38629436,
       3.29583687], dtype=array_api_strict.float64, device=array_api_strict.Device('device1'))
```

**Comment by lucascolley** [comment]
`xlogy` indeed has an implementation at https://github.com/scipy/scipy/blob/e07054248f403bc93b405bfc210ca224f70761a8/scipy/special/_support_alternative_backends.py#L208-L214 now.

Maybe this is still a problem for functions that hit https://github.com/scipy/scipy/blob/e07054248f403bc93b405bfc210ca224f70761a8/scipy/special/_support_alternative_backends.py#L165-L170 ?

**Comment by rgommers** [comment]
This issue and gh-22680 are pretty much exact duplicates. I commented at https://github.com/scipy/scipy/issues/22680#issuecomment-4878484556 on why I'm closing this one as a duplicate and keeping that one open.
