### ISSUE TITLE
TYP/BUG: sparse: `sparray` does not declare any method

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [scipy/scipy#22432]
### Describe your issue.

While spmatrix does declare abstract (and sometimes real) methods, sparray does not. This means sparray cannot be really used in argument type declarations, as a type checker (pyright / basedpyright) will not realize that methods such as `todense`, addition, extraction of elements and others do exist.

### Reproducing Code Example

```python
from scipy.sparse import sparray
from numpy import ndarray

def make_dense(A: sparray) -> ndarray:
    return A.todense()
```

### Error message

```shell
c:\Users\juanj\src\seemps2\foo.py
  c:\Users\juanj\src\seemps2\foo.py:6:14 - error: Cannot access attribute "todense" for class "sparray"
    Attribute "todense" is unknown (reportAttributeAccessIssue)
1 error, 0 warnings, 0 notes
```

### SciPy/NumPy/Python version and system information

```shell
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.17.0",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-30md4hh3\\overlay\\Lib\\site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-pvv4msva/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include",
      "lib directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-pvv4msva/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib",
      "openblas configuration": "OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=24",
      "pc file directory": "D:/a/scipy/scipy"
    },
    "lapack": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-pvv4msva/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include",
      "lib directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-pvv4msva/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib",
      "openblas configuration": "OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=24",
      "pc file directory": "D:/a/scipy/scipy"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.13.6",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-pvv4msva\\cp313-win_amd64\\build\\venv\\Scripts\\python.exe",
    "version": "3.13"
  }
}
```

**Comment by j-bowhay** [comment]
Any suggestions @jorenham ?

**Comment by jorenham** [comment]
You could instead use `scipy.sparse._base._spbase`, or something like `bsr_array | coo_array | ...`

**Comment by juanjosegarciaripoll** [comment]
Using a base class that is hidden is not really nice. I am not asking for a hack, but rather posing a problem to be fixed in Scipy. Ideally both `sparray` and the deprecated `spmatrix` should be duck typing protocols that enumerate the common methods to all these classes, allowing one to use them as substitutes for the whole sparse hierarchy in arguments and function outputs. As they are right now, they are pointless.

**Comment by jorenham** [comment]
In case you use `scipy-stubs`, you could do something like this (on python 3.12+):

```pyi
type SparseArray[ST: np.generic] = (
	bsr_array[ST]
	| coo_array[ST]
	| csc_array[ST]
	| csr_array[ST]
	| dia_array[ST]
	| dok_array[ST]
	| lil_array[ST]
)
```

**Comment by lucascolley** [comment]
Is it out of scope for that to be provided in scipy-stubs?

**Comment by jorenham** [comment]
> Is it out of scope for that to be provided in scipy-stubs?

At the moment `scipy-stubs` are just stubs. But I've been playing with the thought of additionally adding a collection of runtime-accessible utilities. 
This is what [`django-stubs`](https://github.com/typeddjango/django-stubs/) also does with their additional `django_stubs_ext` package.
If something similar were to be in `scipy-stubs`, then you'd be able to e.g. `from scipy_stubs_ext import SparseArray`

**Comment by lucascolley** [comment]
Okay, let's close this issue as this is now an enhancement request for scipy-stubs 👍

**Comment by ilayn** [comment]
Probably we should keep this open as a feature request. 

Though, the feature requested here is the typical OOP inheritance pattern that we don't necessarily follow (personally I don't see the point of having empty base classes lying around, just to please the IDEs), typing out each sparray type manually might indeed be a nuisance. Or we should do it once so others don't have to. 

However, scripture also says, being explicit is better than implicit. @dschult Any opinions?

**Comment by ev-br** [comment]
From 30000 feet, if this is something for type checkers, and can be solved on the -stubs level, that'd be the best outcome.

**Comment by dschult** [comment]
This looks like a feature request for typing.  This feature was put in place to allow folks to use `isinstance` to check whether a sparse object is a sparse array or a sparse matrix. So it is a public class instead of private and it is a class instead of an attribute (we used to depende on an attribute `_is_array` and maybe we still should...). But having it be a class allows fast checking. That's the history.

Given other recent requests/PRs it might be good to have the `sparray` class be somewhere that allows fast importing (in a top-layer that can take advantage of the lazy-loading of the rest of scipy.sparse). But that is really different from this request for a protocol.  I think using `_sp_base` and `issparse()` are probably the best we have right now for those aspects of this request.

**Comment by flying-sheep** [comment]
I filed this issue now: https://github.com/scipy/scipy-stubs/issues/2093

but yeah, it could have been solved before by having `sparray` and `spmatrix` inherit from `_spbase`

**Comment by flying-sheep** [comment]
So since this has been closed in scipy-stubs: do you agree that we should fix this here by having `spmatrix` and `sparray` inherit from `_spbase`?

Then that can be done in the stubs as well, and users can finally just do `if isinstance(m, sparray | spmatrix): m = m.toarray()` as they always wanted.

**Comment by jorenham** [comment]
> do you agree that we should fix this here by having `spmatrix` and `sparray` inherit from `_spbase`?

I would also prefer this solution. My earlier idea in https://github.com/scipy/scipy/issues/22432#issuecomment-2623053057 is closer to a workaround than to a solution. It would also require users to install an additional runtime dependency, which isn't ideal, to say the least.

So if I may be so bold, I'll go ahead and re-open this.

**Comment by jorenham** [comment]
> From 30000 feet, if this is something for type checkers, and can be solved on the -stubs level, that'd be the best outcome.

So to avoid any confusion, this can't be solved on the `-stubs` level alone.

**Comment by dschult** [comment]
Let me see if I understand this trouble here...   (I think I still don't understand the motivating issue here)
Is it: 
1) you want to find a type specification for `sparray` that works nicely, or
2) you want a scipy.sparse object/type to represent all sparse array types.

It looks to me like the original post example is trying to use `sparray` to solve 2).  And it doesn't do that.

Couldn't scipy-stubs create a SparseArray type that includes all the public array classes?

Also -- will this problem disappear after spmatrix is removed? What will be missing at that point?

**Comment by flying-sheep** [comment]
I want an `isinstance` check that tells me if I can do `obj.tocsc()`.

Effectively `isinstance(obj, sparray | spmatrix)` does that, as there are no `_spbase` subclasses apart from those. But `sparray` (and `spmatrix`) aren’t true subclasses of `_spbase`.

They should be so I can do that instance check.

**Comment by jorenham** [comment]
To expand a bit on what @flying-sheep said, this will be rejected by type-checkers:

```py
def f(obj: sparray | np.ndarray):
    if isinstance(obj, sparray):
        x = obj.tocsr()  # ❌ 
    # --snip--
```

The type-checkers are right about complaining here: because `sparray.tocsr` indeed does not exist. So even though `sparray` (and `spmatrix`) are part of the public `scipy.sparse` API, they are kinda misleading in this (static typing) sense.

By having `sparray` (and `spmatrix`) inherit from `_spbase`, this will no longer be a problem.

**Comment by dschult** [comment]
What is the reason for the restriction that this be an isinstance check?
Wouldn't `issparse(A)` be sufficient to see if you can do `A.tocsc()`?

**Comment by jorenham** [comment]
`issparse` only checks if the instance is a `SparseABC`, which has all of the same issues as `sparray` and `spbase` because it also doesn't have `_spbase` as superclass. So typecheckers will treat `issparse(A)` as equivalent to `isinstance(A, SparseABC)`.

**Comment by dschult** [comment]
Got it -- how about:
`isinstance(obj, bsr_array | csr_array | csc_array | coo_array |  dia_array | dok_array | lil_array)`
I'm just trying to understand the restrictions...

**Comment by jorenham** [comment]
That works, but is very impractically clunky. It also doesn't solve the issue of `sparray` and `spmatrix` still being misleading, and I've this go wrong in several libraries in the wild now. That's no surprise if you think about it, because `sparray` is the public API class that's the common *nominal* denominator of all sparse `*_array`s, so it's only natural to expect that `sparray` then also describes the common *interface*. But in reality; that interface is hidden away somewhere in the disjoint and private `_spbase` class. 

Maybe I'm missing something, but I don't think that using `_spbase` as baseclass for `sparray` and `spmatrix` will cause an issues, which should be a 2-line change: to me that seems like an easy win 🤷‍♂️.

**Comment by dschult** [comment]
I think the idea at the time (years ago now) was that we would rename _spbase as sparray once spmatrix went away. I don't pretend to understand the implications here for typing -- but I'm learning (Thank you!).

So if I understand correctly, making _spbase be a super class of sparray would allow static typing to check that all `obj` which are instances of `sparray` would be able to successfully call the method `obj.tocsr`.  The `sparray` class is no longer a Mixin class. It becomes a full fledged class.

Questions:
- Does static typing work with any Mixin classes? Do they need to never be checked using isinstance?
- Could the static typing system introduce a SparseArray type that somehow maps to any of the 7 sparray classes? Then can we use stubs to make sparray of type SparseArray? probably showing my ignorance here.

Anyway, I'm fine with making that change to the sparray and spmatrix classes -- but would want someone with more insight to state that it doesn't have any downsides. @jorenham are you confident that this doesn't have any downsides via e.g. diamond shaped inheritance or performance issues?

**Comment by flying-sheep** [comment]
>  would rename _spbase as sparray once spmatrix went away

Great! So there's really nothing that speaks against making it a common base class of both sparray and spmatrix in the meantime.

> Does static typing work with any Mixin classes?

Static typing only knows superclass relations. So today, a block of code that is guarded by `if is instance(x, sparray):` can't do anything with `x` as far as the type checker is concerned, as `sparray` has no methods, no properties, no superclass, no nothing. 

If you do `if isinstance(x, csr_array | csc_array | csr_matrix | csc_matrix):`, you can do things that all these classes support, i.e. access `.indices` and so on.

> Could the static typing system introduce a SparseArray type that somehow maps to any of the 7 sparray classes?

That's just confusing if it doesn't exist at runtime. And there's no reason to if we *could* just make `sparray` really inherit all these methods at runtime.

> are you confident that this doesn't have any downsides via e.g. diamond shaped inheritance or performance issues?

No why would it? I've never had any issue with diamond inheritance, and we have a super clear hierarchy here, I'm very sure there's no issue. 

The only thing that's possible is that if the file structure is convoluted, there might be circular import issues, but if the import hierarchy matches the inheritance hierarchy, everything works out.

**Comment by dschult** [comment]
The `issparse` and `SparseABC` are housed in `_lib` so they are defined early in the import process and can then be used by other parts of scipy before the `sparse` suite is imported. Would you want/need `SparseABC` to also be a subclass of `_spbase`? If not, I don't think there will be any import difficulties.  :)

**Comment by jorenham** [comment]
> [@jorenham](https://github.com/jorenham) are you confident that this doesn't have any downsides via e.g. diamond shaped inheritance or performance issues?

There's no metaclass voodoo (e.g. `abc.ABC`), and no `__slots__`, so I (also) don't expect this to lead to any measurable performance regressions or other issues. 

A quick check shows that the Python runtime doesn't mind some diamonds:

```
In [1]: class _spbase:
   ...:     def tocsr(self):
   ...:         return "csr"
   ...: class sparray(_spbase): ...

In [2]: class _lil_base(_spbase): ...

In [3]: class lil_array(_lil_base, sparray): ...

In [4]: x = lil_array()

In [5]: x.tocsr()
Out[5]: 'csr'
```

**Comment by flying-sheep** [comment]
Yeah, e.g. pathlib has a nice non-tree-shaped hierarchy like this

![](https://docs.python.org/3/_images/pathlib-inheritance.png)

> SparseABC

Tbf, I don’t understand what that’s there for. Usually ABCs have 3 purposes:

- define a some abstract methods that one needs to implement to be a subclass
- serve as an extension point for 3rd parties (who can subclass ABCs and implement the methods)
- maybe add some mixin methods that depend on the abstract ones to implement extra functionality.

I feel like making SparseABC a real useful ABC is a bigger task than this one and needs more design work.

And honestly, I feel like instead of doing that, scipy should work together with pydata to create a “sparse array api” extension spec, but that’s an even bigger task.

**Comment by lucascolley** [comment]
> Tbf, I don’t understand what that’s there for

As Dan mentioned, it is there to make `issparse` work without needing to import `scipy.sparse`.

EDIT: see https://github.com/scipy/scipy/issues/22382 for the history

**Comment by dschult** [comment]
This desire for a change in inheritance seems to stem from the current static typing tools lack of handling of Mixin classes appropriately. Perhaps this is something the types folks at cPython are working on?  They have eventually solved most of the types short-comings before. I'd prefer not to have static typing concerns influence dynamic class design choices. But I'm willing to bend if other sparse maintainers want to make the change.  I also think this will all go away once `spmatrix` is removed.

**Comment by jorenham** [comment]
> This desire for a change in inheritance seems to stem from the current static typing tools lack of handling of Mixin classes appropriately. Perhaps this is something the types folks at cPython are working on?

I think you misunderstand: mixin classes are handled correctly by static type-checkers, so there's nothing to fix; they're behaving soundly. The only place this can actually be fixed is in SciPy itself, i.e. using the `_spbase`-as-baseclass for `sparray` and `spmatrix` solution that was proposed here.

**Comment by jorenham** [comment]
For example, consider this (rather silly) example:

```py
from scipy.sparse import sparray

class Spam(sparray):
   pass

def do_something_if_sparse(x):
    if isinstance(x, sparray):
        return x.tocsr()
    return None

do_something_if_sparse(Spam())  # will raise at runtime
```

There's a similar problem for `issparse`:

```py
from scipy._lib._sparse import SparseABC
from scipy.sparse import issparse

class Ham(SparseABC): ...

def do_something_else_if_sparse(x):
    if issparse(x):
        return x.tocsr()
    return None

do_something_else_if_sparse(Ham())  # will raise at runtime
```

In both cases, the passed instances have no `tocsr` method, because neither `sparray` nor `SparseABC` defines them. It is therefore *type-unsafe* to assume otherwise. It's even impossible for type-checkers to known that the `tocsr` *could* exist because it simply isn't defined on `sparray` or `SparseABC`. So type-checkers are right to report an error in these cases.
