### ISSUE TITLE
OptimizeResult from minimize_scalar (Brent's method) missing attributes or incorrectly documented

### ISSUE THREAD

**Issue by tloredo** [scipy/scipy#4630]
From the mimize_scalar docstring:

```
Returns
-------
res : OptimizeResult
    The optimization result represented as a ``OptimizeResult`` object.
    Important attributes are: ``x`` the solution array, ``success`` a
    Boolean flag indicating if the optimizer exited successfully and
    ``message`` which describes the cause of the termination. See
    `OptimizeResult` for a description of other attributes.
```

But the result does not have `success` or `message` attributes.  From the source for optimize._minimize_scalar_brent():

```
return OptimizeResult(fun=fval, x=x, nit=nit, nfev=nfev)
```

So the returned value is indeed an OptimizeResult object, but it does not have all of the "important attributes" defined.

A quick fix would be to modify the minimize_scalar docstring to correctly identify the OptimizeResults attributes that are guaranteed to be defined.  But it appears that throughout optimize, a minimal set of attributes is presumed to be defined for all optimization results, so a better fix may be to make sure that minimize_scalar always defines the "important attributes" specified in the docstring.

**Comment by dlax** [comment]
It should be possible to detect that the maximum number of iterations has been exceeded in `Brent.optimize()`. For instance, just add an `else` clause to the `while` loop setting a dedicated attribute, and retrieve it from the caller which builds the `OptimizeResult`.

**Comment by adbugger** [comment]
With the last patch, this issue seems to have been fixed. If not, is it ok to take it and work on?

**Comment by mdhaber** [comment]
`message` is present only in output from `bounded`:
```
import scipy.optimize
for method in ["brent", "golden", "bounded"]:
  print(method + ":")
  print(scipy.optimize.minimize_scalar(lambda x: x**2, method = method, bounds = [-10, 10]))
```

Solution should be to add `message`, since [`OptimizeResult` documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html) specifies that it will be an attribute of an `OptimizeResult`.

**Comment by mdhaber** [comment]
@MiroFurtado 
I'm not seeing a problem with `basinhopping`:
```
print(scipy.optimize.basinhopping(lambda x: x**2, x0 = [1]))
```
It has:
```
  message: 'Optimization terminated successfully.'
```

**Comment by WarrenWeckesser** [comment]
@mdhaber, the problem with the return value from `basinhopping` is that it doesn't have the `success` attribute.  This was just reported in a question on stackoverflow: https://stackoverflow.com/questions/59598917/how-to-access-success-attribute-of-optimizeresult-instance-returned-from-scipy

E.g.
```
In [2]: res = basinhopping(lambda x: x**2, x0=1)                                                             

In [3]: res.success                                                                                          
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+1984f97-py3.7-macosx-10.7-x86_64.egg/scipy/optimize/optimize.py in __getattr__(self, name)
    117         try:
--> 118             return self[name]
    119         except KeyError:

KeyError: 'success'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-1c23ad034239> in <module>
----> 1 res.success

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+1984f97-py3.7-macosx-10.7-x86_64.egg/scipy/optimize/optimize.py in __getattr__(self, name)
    118             return self[name]
    119         except KeyError:
--> 120             raise AttributeError(name)
    121 
    122     __setattr__ = dict.__setitem__

AttributeError: success
```

And, as in the initial report in this issue, `minimize_scalar` still does not set the `message` attribute`

```
In [4]: res = minimize_scalar(lambda x: x**2, [-1, 3])                                                       

In [5]: res.message                                                                                          
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+1984f97-py3.7-macosx-10.7-x86_64.egg/scipy/optimize/optimize.py in __getattr__(self, name)
    117         try:
--> 118             return self[name]
    119         except KeyError:

KeyError: 'message'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-5-ffaa636607ae> in <module>
----> 1 res.message

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+1984f97-py3.7-macosx-10.7-x86_64.egg/scipy/optimize/optimize.py in __getattr__(self, name)
    118             return self[name]
    119         except KeyError:
--> 120             raise AttributeError(name)
    121 
    122     __setattr__ = dict.__setitem__

AttributeError: message

```

This is with the development version of scipy:
```
In [6]: import scipy                                                                                         

In [7]: scipy.__version__                                                                                    
Out[7]: '1.5.0.dev0+1984f97'
```

**Comment by mdhaber** [comment]
Ah ok.

**Comment by andyfaff** [comment]
I'm not sure what an `OptimizeResult.success` attribute means in the context of `basinhopping`; it's not clear what a fail consists of.

- most of the fault conditions in setup are done by raising Exceptions rather than a success flag being set.
- if there are local minimisation failures they are noted in BasinHoppingRunner, but they don't necessarily mean that the entire run is a failure as other local minimisations may have worked.

Still, I would expect that attribute to be set.

**Comment by dbratell** [comment]
Just setting it to true might be ok? Just so that the return object fulfills the `OptimizeResult`.

**Comment by Mazensayed91** [comment]
I think adding this line maybe useful

![image](https://user-images.githubusercontent.com/54520113/117089873-102bd480-ad57-11eb-8fdd-cbe50f119479.png)
