### ISSUE TITLE
bicg returns last iterate, not the smallest-residue vector

### ISSUE THREAD

**Issue by KvZiegelei** [scipy/scipy#5022]
To what extent have the iterative solvers actually been used on practical applications? We are trying them one by one on a fairly simple 3D acoustic equation, and can only get the _cg_-routine to work out of the box, even for very small lattices. This is most likely our faults, but the setup we use for _cg_ (leading to quite satisfactory performance) does not converge for the other solvers.

**Comment by pv** [comment]
If you mean whether the algorithms are widely used --- yes, they are well-known standard methods.

**Comment by KareOlaussen** [comment]
I didn't mean the algorithms. I ment the 8 iterative solver routines in *scipy.sparse.linalg*. Of these, *cg* performs at expected (and "out-of-the box"), better with a good initial guess and better with a preconditioner, in particular for large problems (like a system of linear size 2^24). But we have not (yet) been able to get any of the 7 other routines to work satisfactory (mostly not at all), except for problems of uninterestingly small size (linear size 2^9 or smaller).

Therefore, before embarking on a more complete investigation and experimentation with parameters, we would like to know if anyone has used *these* routines on real-world problems. Do you know?

In contrast, the *eigsh*  eigenvalue  routine works much better than expected, straight out of the box :-)

**Comment by pv** [comment]
The routines are these: http://www.netlib.org/templates/ I do not think we have are available statistics on how widely this particular implementation has been used. On the other hand, there have been no complaints on substandard performance either.

Myself, I've only needed GMRES for medium size problems (2^18) and haven't encountered significant problems with it.

**Comment by pv** [comment]
If you find that some of the methods work worse than they should for some problems, then that *would* be very useful to know.

**Comment by KareOlaussen** [comment]
It is good to known that a routine works for others. The behavior is very likely problem dependent. (We are trying to solve the acoustic equation, with position dependent the speed of sound, in the frequency domain.) I will post results when we have something more definite to say.

Here is a paper were we successfully used the eigsh routine: http://arxiv.org/pdf/1503.04607v1.pdf

**Comment by pv** [comment]
For what it's worth, I get for a 2^19 x 2^19 complex nonsym problem and fixed maxiter same results as in Matlab for cgs, bicg, bicgstab, gmres, qmr down to rounding error (also w/ precond; didn't have memory to test bicg/qmr though).

**Comment by KareOlaussen** [comment]
We are making progress. The only obvious problem at present is that *bicg* does not seem to return the full solution vector, but what looks like the last correction to the solution vector. Do you observe such behavior?  We are running under Python 3.4.3.

We now get essentially the same results from *cg* and *gmres*. (Actually, *cg* is not guaranteed to work on our problem, since our *A* is not positive definite. But it still performs best).

**Comment by pv** [comment]
I noticed bicg does not return the smallest-residual vector it
encounters, but rather the last iterate --- which matters when the
algorithm runs to instability. If terminated with maxiter at the best
iterate, the results agreed with Matlab implementation (which apparently
always returns the best iterate).

**Comment by KareOlaussen** [comment]
I have checked this on a small well-behaved system (16 x 16 matrix), where the process terminates after 6 iterations. The two first iterations are about the same for *cg* and *bicg*. Then the *bicg* solution decays towards zero. It is a bit mysterious what makes the process stops after 6 iterations, seemingly because the solution becomes small.

**Comment by KareOlaussen** [comment]
Pauli. Don't worry about our problems. We are using LinearOperator instead of a sparse matrix. The fact that *cg* (which uses *matvec* only) works, and *bicg* (which uses both *matvec* and *rmatvec*) does not, is an indication that some data arrays have been overwritten (too early).

**Comment by KareOlaussen** [comment]
The *bicg*-problem does not quite disappear. It seems that *bicg* does work correctly when given a starting guess *x0*. Here is a 2x2 demonstration:

    A = numpy.array([[1,0],[0,2]])
    b = numpy.array([1, 2])
    xe = numpy.array([1,1]) # Exact solution
    x = bicg(A,b)[0]
    y = bicg(A, b, x0=xe)[0]
    print (x, y)  # Result: [ 1.  1.] [ -6.57909941e-17   3.58766514e-17]

**Comment by PieterDecleer** [comment]
I have just encountered the above issue with bicg. The solution to the linear system I am trying to solve tends to zero when I am using an initial guess. Using bicg without the initial guess (or zero inital guess) works fine as well as cg with and without an initial guess. I encountered this issue both in python 2.7 using scipy 1.2.1 and in python 3.6.8 using scipy 1.3.0.
Has this issue been addressed in any way?

**Comment by dut09** [comment]
As of today, the issue with initial guesses seems not fixed. I tried scipy 1.3.2 and python 3.7:
```
import matplotlib.pyplot as plt
import numpy as np
from scipy.sparse.linalg import bicg, bicgstab, cgs, gmres, lgmres, minres, qmr

n = 42
np.random.seed(0)
A = np.random.uniform(-1, 1, (n, n))
b = np.random.uniform(-1, 1, n)
x0 = np.random.uniform(-1, 1, n)
x_sol = np.linalg.solve(A, b)
assert np.allclose(A @ x_sol, b)

for solver, name in [(bicg, 'bicg'), (bicgstab, 'bicgstab'), (cgs, 'cgs'), (gmres, 'gmres'), (lgmres, 'lgmres'), (minres, 'minres'), (qmr, 'qmr')]:
    x, info = bicg(A, b)
    print(name, 'not using x0: Ax - b:', np.linalg.norm(A @ x - b))

    x, info = bicg(A, b, x0=x0)
    print(name, 'using x0: Ax - b:', np.linalg.norm(A @ x - b))
```
and here is the output:
```
bicg not using x0: Ax - b: 1.2703541310134373e-05
bicg using x0: Ax - b: 3.772059540929398
bicgstab not using x0: Ax - b: 1.2703541310134373e-05
bicgstab using x0: Ax - b: 3.772059540929398
cgs not using x0: Ax - b: 1.2703541310134373e-05
cgs using x0: Ax - b: 3.772059540929398
gmres not using x0: Ax - b: 1.2703541310134373e-05
gmres using x0: Ax - b: 3.772059540929398
lgmres not using x0: Ax - b: 1.2703541310134373e-05
lgmres using x0: Ax - b: 3.772059540929398
minres not using x0: Ax - b: 1.2703541310134373e-05
minres using x0: Ax - b: 3.772059540929398
qmr not using x0: Ax - b: 1.2703541310134373e-05
qmr using x0: Ax - b: 3.772059540929398
```
Looks like none of these solvers give the correct solution when x0 is provided.

**Comment by pv** [comment]
You call bicg(...) and not solver(...) in the for loop?

**Comment by pv** [comment]
Moreover, solvers assuming symmetry do not work on nonsymmetric problems, and n=42 random matrix with default maxiter and no preconditioning is unlikely to be solved in any case.

**Comment by dut09** [comment]
Yeah I should have called solver instead of bicg in my for loop. I have updated the test code as follows:
```
import matplotlib.pyplot as plt
import numpy as np
from scipy.sparse.linalg import bicg, bicgstab, cgs, gmres, lgmres, minres, qmr

n = 42
A = np.random.uniform(-1, 1, (n, n))
b = np.random.uniform(-1, 1, n)
x0 = np.random.uniform(-1, 1, n)
x_sol = np.linalg.solve(A, b)
assert np.allclose(A @ x_sol, b)

for solver, name in [(bicg, 'bicg'), (bicgstab, 'bicgstab'), (cgs, 'cgs'), \
    (gmres, 'gmres'), (lgmres, 'lgmres'), (minres, 'minres'), (qmr, 'qmr')]:
    x, info = solver(A, b)
    print(name, info, 'not using x0: Ax - b:', np.linalg.norm(A @ x - b))

    x, info = solver(A, b, x0=x0)
    print(name, info, 'using x0: Ax - b:', np.linalg.norm(A @ x - b))
```
and my output is
```
bicg 0 not using x0: Ax - b: 6.427763873948325e-06
bicg 0 using x0: Ax - b: 3.758110126975673
bicgstab -10 not using x0: Ax - b: 59.517776343386075
bicgstab -10 using x0: Ax - b: 23.050127412860686
cgs 0 not using x0: Ax - b: 3.4035853127921554e-05
cgs 0 using x0: Ax - b: 2.3519036047919115e-05
gmres 420 not using x0: Ax - b: 2.6128474069420964
gmres 420 using x0: Ax - b: 6.043612320810984
lgmres 1000 not using x0: Ax - b: 1.2854787103668692
lgmres 1000 using x0: Ax - b: 2.62623133342444
minres 210 not using x0: Ax - b: 14.441343392466882
minres 210 using x0: Ax - b: 14.441343392466882
qmr 0 not using x0: Ax - b: 3.0904828571747333e-05
qmr 0 using x0: Ax - b: 3.758110074972171
```
I am still concerned with the output. For example, if I look at the first two lines:
```
bicg 0 not using x0: Ax - b: 6.427763873948325e-06
bicg 0 using x0: Ax - b: 3.758110126975673
```
The returned info is 0 so the problem is thought to be successfully solved in both case (using/not using x0), but the returned x is far from being correct when an initial guess x0 is provided. The same thing happened to csg and qmr.
For bicgstab, -10 means it thinks the input is illegal, so I can accept that it ended up not solving this problem.

**Comment by pv** [comment]
Yes, I agree bicg and qmr don't work right with x0= given.

**Comment by dut09** [comment]
Thank you for the clarification! Now I understand the issue better and I agree the output for the other solvers is more or less expected.
