### ISSUE TITLE
FAIL: test_decomp_update.TestQRdelete_f.test_delete_last_p_col

### ISSUE THREAD

**Issue by dabliss** [scipy/scipy#5335]
I have the most up-to-date development version of `scipy` installed on two machines.  Running `scipy.test()` causes no test failures on one machine, and a single test failure on the other:

    ====================================================================== 
    FAIL: test_decomp_update.TestQRdelete_f.test_delete_last_p_col
    ----------------------------------------------------------------------     
    Traceback (most recent call last):   File
    "/usr/local/anaconda/lib/python2.7/site-packages/nose/case.py", line
    197, in runTest
        self.test(*self.arg)   File "/home/despo/dbliss/lib/python2.7/site-    packages/scipy/linalg/tests/test_decomp_update.py",    
    line 328, in test_delete_last_p_col
        assert_unitary(q1)   File "/home/despo/dbliss/lib/python2.7/site-    packages/scipy/linalg/tests/test_decomp_update.py",
    line 21, in assert_unitary
        assert_allclose(aTa, np.eye(a.shape[1]), rtol=rtol, atol=atol)   File
    "/home/despo/dbliss/.local/lib/python2.7/site-packages/numpy/testing/utils.py",
    line 1297, in assert_allclose
        verbose=verbose, header=header)   File "/home/despo/dbliss/.local/lib/python2.7/site-    packages/numpy/testing/utils.py",
    line 665, in assert_array_compare
        raise AssertionError(msg) AssertionError:  Not equal to tolerance rtol=0.0001, atol=2.38419e-07

    (mismatch 100.0%)  x: array([[  9.999999e-01,   1.746230e-08, 
    -1.490116e-08,   1.490116e-08,
             -6.146729e-08,  -6.332994e-08,   3.352761e-08,   7.450581e-08,
              3.352761e-08,   2.142042e-08,  -4.097819e-08,   4.656613e-08],...  y: array([[ 1.,  0.,  0.,  0.,      0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
           [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
           [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],...

    ---------------------------------------------------------------------- 
    Ran 18599 tests in 253.381s

    FAILED (KNOWNFAIL=97, SKIP=1165, failures=1)`

Here are some relevant details for the machine on which the test PASSES:

    $ python -c 'import scipy; print scipy.__config__.show()'
    lapack_info:
        libraries = ['lapack']
        library_dirs = ['/usr/lib']
        language = f77
    lapack_opt_info:
        libraries = ['lapack', 'blas']
        library_dirs = ['/usr/lib']
        language = f77
        define_macros = [('NO_ATLAS_INFO', 1)]
    openblas_lapack_info:
      NOT AVAILABLE
    blas_info:
        libraries = ['blas']
        library_dirs = ['/usr/lib']
        language = f77
    atlas_3_10_blas_threads_info:
      NOT AVAILABLE
    atlas_threads_info:
      NOT AVAILABLE
    atlas_3_10_threads_info:
      NOT AVAILABLE
    atlas_blas_info:
      NOT AVAILABLE
    atlas_3_10_blas_info:
      NOT AVAILABLE
    atlas_blas_threads_info:
      NOT AVAILABLE
    openblas_info:
      NOT AVAILABLE
    blas_mkl_info:
      NOT AVAILABLE
    blas_opt_info:
        libraries = ['blas']
        library_dirs = ['/usr/lib']
        language = f77
        define_macros = [('NO_ATLAS_INFO', 1)]
    atlas_info:
      NOT AVAILABLE
    atlas_3_10_info:
      NOT AVAILABLE
    lapack_mkl_info:
      NOT AVAILABLE
    mkl_info:
      NOT AVAILABLE
    None
    $ uname -a
    Linux dan-laptop 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:12:08 UTC 2015 i686 i686 i686     GNU/Linux
    $ gcc --version
    gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    $ ipython
    Python 2.7.6 (default, Jun 22 2015, 18:00:18) 
    Type "copyright", "credits" or "license" for more information.

    IPython 1.1.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: import numpy as np

    In [2]: np.__version__
    Out[2]: '1.9.3'

    In [3]: import scipy

    In [4]: scipy.__version__
    Out[4]: '0.17.0.dev0+7dd2b91'

    In [5]: import cython

    In [6]: cython.__version__
    Out[6]: '0.23.3'

Here are the same details for the machine on which the test FAILS:

    dbliss@nx3[~]> python -c 'import scipy; print scipy.__config__.show()'
    lapack_info:
        libraries = ['lapack']
        library_dirs = ['/usr/lib64']
        language = f77
    lapack_opt_info:
        libraries = ['lapack', 'blas']
        library_dirs = ['/usr/lib64']
        language = f77
        define_macros = [('NO_ATLAS_INFO', 1)]
    openblas_lapack_info:
      NOT AVAILABLE
    blas_info:
        libraries = ['blas']
        library_dirs = ['/usr/lib64']
        language = f77
    atlas_3_10_blas_threads_info:
      NOT AVAILABLE
    atlas_threads_info:
      NOT AVAILABLE
    atlas_3_10_threads_info:
      NOT AVAILABLE
    atlas_blas_info:
      NOT AVAILABLE
    atlas_3_10_blas_info:
      NOT AVAILABLE
    atlas_blas_threads_info:
      NOT AVAILABLE
    openblas_info:
      NOT AVAILABLE
    blas_mkl_info:
      NOT AVAILABLE
    blas_opt_info:
        libraries = ['blas']
        library_dirs = ['/usr/lib64']
        language = f77
        define_macros = [('NO_ATLAS_INFO', 1)]
    atlas_info:
      NOT AVAILABLE
    atlas_3_10_info:
      NOT AVAILABLE
    lapack_mkl_info:
      NOT AVAILABLE
    mkl_info:
      NOT AVAILABLE
    None
    dbliss@nx3[~]> uname -a
    Linux nx3.priv 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64     x86_64 GNU/Linux
    dbliss@nx3[~]> gcc --version
    gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
    Copyright (C) 2010 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    dbliss@nx3[~]> ipython
    Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Sep 15 2015, 14:50:01) 
    Type "copyright", "credits" or "license" for more information.

    IPython 3.2.0 -- An enhanced Interactive Python.
    Anaconda is brought to you by Continuum Analytics.
    Please check out: http://continuum.io/thanks and https://anaconda.org
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: import numpy as np

    In [2]: np.__version__
    Out[2]: '1.9.3'

    In [3]: import scipy

    In [4]: scipy.__version__
    Out[4]: '0.17.0.dev0+7dd2b91'

    In [5]: import cython
 
    In [6]: cython.__version__
    Out[6]: '0.23.3'

**Comment by dabliss** [comment]
Some relevant stackoverflow questions (in order):

http://serverfault.com/questions/727430/possibly-installing-and-using-a-specific-version-of-python

http://stackoverflow.com/questions/33003710/how-can-i-figure-out-how-scipy-is-generating-its-c-code

http://stackoverflow.com/questions/33004894/how-to-change-the-version-of-lapack-to-which-scipy-is-linked

**Comment by rgommers** [comment]
Deja vu all over again....

@dabliss I'm not at all sure that your LAPACK version is the issue. Your GCC versions are not the same for example; 4.8.4 on your working install versus 4.4.7 on your failing install. 

For the 0.16.0 release we had a lot of issues with this function, but I thought that it was all fixed now. Any remaining bug (if it's even a Scipy bug) is probably very hard to reproduce and therefore very hard for us (@ewmoore has done all the heavy lifting on this) to fix.

You did quite a lot of digging already and if you can debug the issue that would be great, but the path of least resistance here is deciding that you don't need to use the ``qr_delete`` function and leave things as they are on your machine. There is nothing else in Scipy that depends on ``qr_delete``, so unless you use it directly you'll be fine.

**Comment by dabliss** [comment]
@rgommers thanks for the reply.  do you guys have any sense of which GCC versions are supported and which (potentially) aren't?  and for my GCC installation, does it make a difference to scipy what configuration options i use?  what about the GCC dependencies?  is it worth looking into any specific ones to see whether they differ on my two machines?  (@ewmoore?)

i don't like the idea of having a test that fails (even if it isn't that big of a deal, practically speaking), so i'm going to make an effort to get this to pass.  right now i'm installing GCC version 4.8.4 on the machine on which the test fails (the one that had 4.4.7) -- using the generally recommended configuration options.  i'll report whether that removes the error.

**Comment by rgommers** [comment]
At the moment GCC >= 4.4 should be working. 4.2 doesn't anymore I believe. However, the code that's failing here is new in 0.16.0 and fairly low-level, so it's possible that it gives an issue with gcc 4.4 or with some compiler flags that you happen to have set that are nonstandard.

**Comment by dabliss** [comment]
trying to install `gcc` version 4.8.4 under my local account on the computing cluster where the scipy test fails for me has proven to be a disaster.  i've had to install a bunch of dependencies (GMP, MPFC, MPC, glibc, . . .) and the installation of the last of these -- glibc -- failed, creating a broken installation that has screwed up my account generally.  (i now need to ssh into my account from elsewhere and edit my .bashrc so that the broken installation is not used.)

i spoke with my system administrator about this, and she said that our computing cluster uses the versions of the C libraries and compiler that come standard with CentOS6/RHEL6.

it seems to me that scipy should work with a standard OS like this.  so i'm going to give up on making (what have turned out to be) radical changes on my computing cluster, and leave the onus on scipy to become compatible with CentOS6/RHEL6 -- which is apparently a very common OS for computing clusters.  (or, if that test isn't especially important, maybe it should be edited or removed.)

if anyone has evidence that something more specific about my machine is causing this error to occur for me -- that it's not a general issue with CentOS6/RHEL6 -- i'd be happy to hear and address that.

**Comment by ewmoore** [comment]
For what it's worth, I wrote the code in question on a RHEL6 machine, and
compiled it with the default compiler, installed using yum. When I tested
it, I used the old version of atlas that redhat provides and some git version
of openBLAS.

I'm certainly willing to work with you and clean this up, however, I no
longer have access to that machine, and current don't have a development
environment.

**Comment by dabliss** [comment]
@ewmoore thanks for the reply.  if the code was originally written (and the tests passed) with the version of `gcc` i have default on my machine, then i guess there's no point in trying to upgrade it.  what would you recommend i do?  it sounds like the one thing you had that wasn't default was openBLAS.  maybe i should try to install a newer version of that?  is there a way for us to tell first whether my current version of BLAS is likely to be unsupported?

**Comment by ewmoore** [comment]
Looking at your first message, I think that the test tolerance may just be
too tight.  Can you try adjusting the atol used in assert_unitary? It is
line 16 of scipy/linalg/tests/test_decomp_update.py. It looks to that it
should be more like 5*eps.  If changing it to 5 doesn't fix the test
failure, what value does?

I think that the routine works just fine here, but the differences in
hardware, blas/lapack versions and the overly tight test tolerance result
in this failure.

**Comment by dabliss** [comment]
@ewmoore since you're suggesting i make changes to the source code, i figured i should fork the repo (instead of just cloning it).  i also figured i should move to (i.e., install) the most recent commit.  as an example of one of life's wonderful mysteries, that test now (presumably) passes, and a *different* one fails:

```
======================================================================
FAIL: test_odeint_jac.test_odeint_full_jac
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/despo/dbliss/lib/python2.7/site-packages/scipy/integrate/tests/test_odeint_jac.py", line 71, in test_odeint_full_jac
    check_odeint(JACTYPE_FULL)
  File "/home/despo/dbliss/lib/python2.7/site-packages/scipy/integrate/tests/test_odeint_jac.py", line 66, in check_odeint
    assert_allclose(yfinal, y1, rtol=1e-12)
  File "/home/despo/dbliss/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/despo/dbliss/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-12, atol=0

(mismatch 100.0%)
 x: array([  4.266167e-04,   2.668761e-05,   2.054494e-06,   2.566184e-08,
         3.395213e-10])
 y: array([  4.266167e-04,   2.668761e-05,   2.054494e-06,   2.566184e-08,
         3.395246e-10])

----------------------------------------------------------------------
Ran 18610 tests in 313.252s

FAILED (KNOWNFAIL=97, SKIP=1165, failures=1)
Out[3]: <nose.result.TextTestResult run=18610 errors=0 failures=1>
```

Since this also seems to be a matter of tolerance, I'm not sure whether I should start a new issue.  In any event, what do you make of the error?

**Comment by rgommers** [comment]
@dabliss a new issue isn't needed. Indeed a test tolerance issue. Can you figure out how much the tolerance should be increased to have the test pass?

**Comment by dabliss** [comment]
@rgommers for this new error, the smallest value for `rtol` that doesn't fail for me is `1e-5`.

(it may be worth noting that a comment in the source code just above the assertion line that fails for me says, "It is likely that yfinal and y1 are *exactly* the same, but we'll be cautious and use assert_allclose.")

unfortunately, getting rid of this error reveals a new one, for the line that follows (i.e., line 67 of `test_odeint_jac.py`):

```
======================================================================
FAIL: test_odeint_jac.test_odeint_full_jac
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/despo/dbliss/lib/python2.7/site-packages/scipy/integrate/tests/test_odeint_jac.py", line 71, in test_odeint_full_jac
    check_odeint(JACTYPE_FULL)
  File "/home/despo/dbliss/lib/python2.7/site-packages/scipy/integrate/tests/test_odeint_jac.py", line 67, in check_odeint
    assert_equal((odeint_nst, odeint_nfe, odeint_nje), (nst, nfe, nje))
  File "/home/despo/dbliss/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 270, in assert_equal
    assert_equal(actual[k], desired[k], 'item=%r\n%s' % (k, err_msg), verbose)
  File "/home/despo/dbliss/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 334, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
item=0

 ACTUAL: 6088
 DESIRED: 6055

----------------------------------------------------------------------
Ran 18612 tests in 230.054s

FAILED (KNOWNFAIL=97, SKIP=1165, failures=1)
Out[3]: <nose.result.TextTestResult run=18612 errors=0 failures=1>
```

**Comment by rgommers** [comment]
Hmm, so not just a small bump in test tolerance to fix it. I'm not very familiar with that code. Maybe @WarrenWeckesser as the original author has a suggestion here.

**Comment by WarrenWeckesser** [comment]
I saw this, and I'll try to take another look this weekend.  It might be hard to reproduce the errors.

**Comment by dabliss** [comment]
I've been updating my version of `scipy` as new commits are made, but I continue to get this one error (only on one of my machines).  Since the error is difficult to reproduce, is there anything I can do on my end to get rid of it?  I'm happy to make any changes to `scipy`'s code that you recommend.  (Or if you can make specific recommendations as far as other software I should install to make my system compatible with `scipy`, I'd be happy to take them.)

**Comment by LBragg** [comment]
Just to add in -- I also am getting this error on RHEL6, when linking against the atlas rpm installed via yum. 

   AssertionError:
   Not equal to tolerance rtol=0.0001, atol=2.38419e-07

   (mismatch 1.38888888889%)

**Comment by rgommers** [comment]
@LBragg you mean the ``odeint`` error and not the ``TestQRdelete`` one, right?

**Comment by WarrenWeckesser** [comment]
The `odeint` test attempts to verify that the python wrapper of LSODA handles the Jacobian properly.  There is a pure Fortran code that uses LSODA to solve a problem with a Jacobian, and there is a Python version that solves the same system, with f2py-generated wrappers of the Fortran code.  The idea is that, as far as LSODA is concerned, the exact same system is being solved, and all the callbacks to the differential equations and Jacobian should be executed in the same order and produce the same results.  In the python version, the calls that LSODA makes to the compute the right-hand-side and the Jacobian go through the python wrappers, but (in theory) the net affect of those wrappers is only that some extra copying is done.  All the actual computations are done by Fortran functions, and in theory both versions should end up computing *exactly* the same thing.

A test like this would have discovered some egregious bugs in the handling of the Jacobian that existed in scipy for a long time, and so far the test has worked well, but I've always been a bit nervous about it.  I may have missed a setting that might cause a difference. Or the test might fail because of the inherent unpredictability of floating point computations (http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html, addendum).

The test that produces this error:
```
AssertionError: 
Items are not equal:
item=0

 ACTUAL: 6088
 DESIRED: 6055
```
is comparing the number of internal steps (that's `item=0`), the number of function evaluations and the number of Jacobian evaluations of the two versions.

I'll review the test again, but it might turn out that, while it works on most systems, we simply can't guarantee that the execution of the two versions of the code will always be exactly the same.

**Comment by WarrenWeckesser** [comment]
FWIW:  I haven't been able to reproduce the `odeint` test failure.  In fact, I changed the `assert_allclose` in the same test to an equality test, and the test passes.  It passed on my Mac (using Anaconda for numpy, etc), an old laptop running Ubuntu 12.04, and on the Travis CI systems.

**Comment by stonebig** [comment]
hi,

Error still there with scipy-0.11.2rc1 ?

````
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import scipy;scipy.test()
Running unit tests for scipy
NumPy version 1.11.2rc1
NumPy relaxed strides checking option: False
NumPy is installed in C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\numpy
SciPy version 0.18.1
SciPy is installed in C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\scipy
Python version 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
````

````
======================================================================
FAIL: test_decomp_update.TestQRdelete_F.test_delete_last_p_col
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\scipy\linalg\tests\test_decomp_update.py", line 328, in test_delete_last_p_col
    assert_unitary(q1)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\scipy\linalg\tests\test_decomp_update.py", line 21, in assert_unitary
    assert_allclose(aTa, np.eye(a.shape[1]), rtol=rtol, atol=atol)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\numpy\testing\utils.py", line 1392, in assert_allclose
    verbose=verbose, header=header)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\numpy\testing\utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=2.38419e-07

(mismatch 1.3888888888888857%)
 x: array([[  1.000000e+00 +0.000000e+00j,  -4.470348e-08 -1.490116e-08j,
         -5.587935e-08 +0.000000e+00j,  -2.793968e-08 +1.490116e-08j,
          7.450581e-09 -2.607703e-08j,  -4.656613e-09 +9.313226e-09j,...
 y: array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],...

----------------------------------------------------------------------
Ran 23059 tests in 1664.624s

FAILED (KNOWNFAIL=61, SKIP=1777, failures=1)
````

**Comment by rgommers** [comment]
> Error still there with scipy-0.11.2rc1 ?

Guess you meant `numpy-1.11.2rc1``. But yes, this is very hard to debug (or even reproduce). It won't depend on numpy version, but will on LAPACK version and platform/compilers.

**Comment by mdhaber** [comment]
I'll go ahead and change the title since the `linalg` label was removed in favor of `integrate`, and we have about [five other issues](https://github.com/scipy/scipy/issues?q=is%3Aissue+is%3Aopen+test_delete_last_p_col) that record problems with `test_delete_last_p_col`.
