### ISSUE TITLE
Custom sampling methods in shgo do not work

### ISSUE THREAD

**Issue by Jwink3101** [scipy/scipy#9943]
My issue is about: custom sampling in shgo

### Reproducing code example:

Trying to use my own sampling method. But to illustrate the problem, will use random. Note, from the docs:

> ```
> sampling_method : str or function, optional
>     Current built in sampling method options are ``sobol`` and
>     ``simplicial``. The default ``simplicial`` uses less memory and provides
>     the theoretical guarantee of convergence to the global minimum in finite
>     time. The ``sobol`` method is faster in terms of sampling point
>     generation at the cost of higher memory resources and the loss of
>     guaranteed convergence. It is more appropriate for most "easier"
>     problems where the convergence is relatively fast.
>     User defined sampling functions must accept two arguments of ``n``
>     sampling points of dimension ``dim`` per call and output an array of
>     sampling points with shape `n x dim`. 
> ```

My code:
```
import numpy as np
import scipy.optimize

# Toy problem
fun = lambda x: (x[1]-0.2)**2 + x[0]
bounds = np.array([[0,+1],
                   [0,+1]])

sample = lambda n,d:np.random.uniform(size=(n,d))

res = scipy.optimize.shgo(fun,bounds,sampling_method=sample)
print(res)
```

### Error message:

Following error with personal information removed and replaces with `[...]`

```
  File "err_demo.py", line 11, in <module>
    res = scipy.optimize.shgo(fun,bounds,sampling_method=sample)
  File "[...]/site-packages/scipy/optimize/_shgo.py", line 420, in shgo
    options=options, sampling_method=sampling_method)
  File "[...]/site-packages/scipy/optimize/_shgo.py", line 459, in __init__
    " Valid methods: {}").format(', '.join(methods)))
ValueError: Unknown sampling_method specified. Valid methods: sobol, simplicial
  ...
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by reneeotten** [comment]
Yes, the input check in the SHGO class is incorrect; it should accept a user-defined function as it appears to do in line 621 (```elif (sampling_method == 'sobol') or (type(sampling_method) is not str):```). 

I suppose that the check for ```sampling_method``` not being a string should be included as a check on line 457. Probably though using ```isinstance``` for the type comparison. Can @Stefan-Endres, the author of the code, perhaps take a look at this? Otherwise, I can probably make a PR at some later point.

**Comment by rgommers** [comment]
Ah yes that is a clear bug.

> Can @Stefan-Endres, the author of the code, perhaps take a look at this? Otherwise, I can probably make a PR at some later point.

Thanks for pinging @Stefan-Endres. He'll want to fix this in his standalone implementation as well.

This seems very straightforward to fix, one liner change + regression test. A PR would be very welcome @reneeotten if there's no response within a couple of days.

**Comment by reneeotten** [comment]
> This seems very straightforward to fix, one liner change + regression test. A PR would be very welcome @reneeotten if there's no response within a couple of days.

@rgommers okay, I will submit a PR this weekend as there has been no response. I did open a PR though to fix another issue with ```shgo``` a few days (see #10114), which also added a test. Can that be reviewed/merged first so that there will be no conflicts, of do you prefer me to add commits to that PR to fix this issue as well?

**Comment by rgommers** [comment]
> Can that be reviewed/merged first so that there will be no conflicts

done:)

**Comment by reneeotten** [comment]
okay, I changed the two lines below (only the first one should be strictly necessary, but changing to ```isinstance``` in the latter would be better as well):
- lines 457:
```
-        if sampling_method not in methods:
+        if isinstance(sampling_method, str) and sampling_method not in methods:
```

- line 621:
```
-        elif (sampling_method == 'sobol') or (type(sampling_method) is not str):
+        elif sampling_method == 'sobol' or not isinstance(sampling_method, str):
```

that  bring us past the ```ValueError```, but still gets stuck a bit later using the example (which I think should work).
```
Traceback (most recent call last):
  File "shgo_custom_sampling_method.py", line 11, in <module>
    res = scipy.optimize.shgo(fun, bounds, sampling_method=sample)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_shgo.py", line 423, in shgo
    shc.construct_complex()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_shgo.py", line 726, in construct_complex
    self.iterate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_shgo.py", line 869, in iterate
    self.iterate_complex()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_shgo.py", line 906, in iterate_delaunay
    self.sampled_surface(infty_cons_sampl=self.infty_cons_sampl)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_shgo.py", line 1233, in sampled_surface
    self.sorted_samples()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/_shgo.py", line 1390, in sorted_samples
    self.Ind_sorted = np.argsort(self.C, axis=0)
AttributeError: 'SHGO' object has no attribute 'C'
```

I did look at the code a bit more, but trying to debug this isn't probably something I can do very quickly...

**Comment by Stefan-Endres** [comment]
Thank you for pinging me (and sorry for the late reply, I did not have internet access last week).

I will take a look at this tonight. Hopefully it shouldn't take too long to fix.

**Comment by Stefan-Endres** [comment]
Hopefully resolved this issue here #10152, currently working for the toy problem proposed, @Jwink3101 please let me know if there are any issues with your real custom sampling method.
